host_name: ENC[AES256_GCM,data:5nttR/qN,iv:Iw3Nb2TDTcOeM6plsHoGGfON7RdFRpT7eNkUNvZkMT8=,tag:Qnouc7JHu4BTzp6eGKVo7g==,type:str]
main_user: ENC[AES256_GCM,data:18A1hw==,iv:meXzIPlMh6LqlBwhjrb7yuGy3QGd6JfLDgiwErcO6CI=,tag:KlbGOPiMkNvpUuiEPP+Kwg==,type:str]
ansible_user: ENC[AES256_GCM,data:EFawfA==,iv:fJ8OHw/MA9spF1DUjjwRYrEIXwxwEFONFhdf+ungfyE=,tag:KHSajg4v3tFMqklYe6O6Ww==,type:str]
podman_userns: ENC[AES256_GCM,data:UCkPL99cqMSuVLBa2k8=,iv:79gTX2SuKLo6+0Ozn3+Ch5TAOVhJ7xlVyXdr7fHsfrE=,tag:wjWY9lxJULOyb3XD8Z8xGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGZqa09YcHpm
            bFZ2NjF6VFJxVkpjU3o3OE5YaFYwU3p5ZndQY1N2b3g3NjFvTlM4dVkzRGt2Zi91
            eDdPUG1vQ2NTRXRlL1V2Tkk5VVNaVC9pSlBhZFpWaGZBTjdYZEJXMkdxRklQakRO
            bHJ6bXdranpzQ1JYc1RrTjBqRFZ3ZHJOYUZYY3ZiN054TDh6Wjl4TURnekl4VXRh
            bVYyVlRWY09vU1piazB5dDV3dXAvMktFZDNxYlV3bG0xYVBDWGdqS3hmYnZHVWhx
            UHRkUkpZdXZqSU5lV2hZUlNoN3ZFV1FoRGN1UlR4aVExaVpIQ3NZYlJUZkhIY2I4
            Sm1nSG03b0RKSnFNRHBzeDh3Qk5qTURyMFEvbHEvbVRzYzJndTdhRkdJeC9LdmdI
            NTIrdnRiYUxNd0Y3TDFUQXA0TlJLQVVPNHR5UjRpVFNma0dyTW9nUWVFSzI1Zmtn
            dllsc1ZEbFZqMmVmVzViMUNnYlMwdmZraUVmanBONk5NMUVYZnZ6NjQ4WnVYVjJX
            L2E3ODJ1Wm82anBuVGRjZ1MrajEwS3I1UmNnSXFocjFwMC9SbU0raDFzc1hSajd6
            OGcxVGJycnZ6Uy84NVFTN2d3S0d0NFN4Zk8zYS91eTBHbnhpOEFjOTVRQzNGOUFB
            ZWVzQ0ZTVFdqUFV1TVR3KzBvVEszM3pXa1crVmZLQmpVQ2NMaVI4L3pWdU9YL05r
            RHVtRi9FdmRnbFpiZ0t2OUhwVGJMcGdwU1hiUktwTjNUK01VREkrbTFCRkgzMkll
            S2dnQ05LKzQrRE5oM0pRNERQZkNJb2ZRU2tnRWxIRC9FQWRBS1MyMzlkMmJ3K25Y
            SDA3OXZkNFhWYXg4alYzN05RTml5WXdUekMxejBSLzhmSFYycVJqdzN0RzZnT0RF
            SjBVR3ZHQjFBd1UzSkoyejk3M011VXhyT3pBRVlzN0VrSGplTEZvaUE4b21hRlZr
            SHRhMHlSYzZQWCs3OTNYc1Y5cm53TDloT1h0RGRDbHpXR3lEWURwV3Z3WmhiUXpT
            amVjZnlrWnBJMUV4bnVIK0ZrYXV4OFVTeS83UXdJdGxOVDg1YnpsbHRVeWN1MlNO
            bWd6cytKUGpodEJKVDljVVFsVzFaNzlobWNVKzF0cEVLMlVzTTUvSDNyN1NwUXlw
            QjZQeW1GTWlVdURtNWtCUUhpcVNUdmZDRUhyYVI1RGtwU1JtWDAvTElFZkJBYWNQ
            ZG5MdjdlZ21ZcW5FRk9scnVraFpXcUZCWW4rQnJrbFRBR2k3a1FqbHFkeXNlQ2ky
            dGZRTjBUeGExcEl2Q1o0bFZEY3Q4QzJHQnJIZExHVkFCWVFQTzU2TndFMEdjeWQx
            djY2T3pIbHlHNWQyQ1dmLzA2L0xTZDZldk9wNk9IMGY1QVJJOHNnNlduRklPb0dv
            V3dlaDArblBFYVpPajArUXlaSzA5clo0RXFVa3JrVXhHT09kSnRhU2pvSUNvTFJG
            aThtdEMyYkxWbnA5eUhFVjZjSEhqRS9iZEVDSXcvVDFkUUR3cHJtYkZVb25aWFlO
            dTl0a2ZRc2ZWUGdLUndua1RrTnNWbmQzYWk5RjF2Q2JoLyt1UGI2alY4ejRPVVFI
            M1RPNnVQeGw2aTlUb1lVLzlJR2pCQUxGS2p3cFRRcUUzM0p5NmsrZFJSWlZIUEVT
            UWRwQTRNSW50OERnMVdpaDRCY2doWTBwWEk3czRETWNEUjVlRmNxOWFIeXBNUmpF
            anNnSUNnY0k1L3F0aS9mV3U3WUZ0bmtEc3VZTCs2WlB0TXJtWTFZWHlVQnY3MWVE
            NlFzYVNPdjJsdmZodHlza3lQa2xnU0xhdER2SFNuK1FVQjBYN2dpdk92ZG1HV0d0
            aTBINVJVNk9TVnpSaWNEUm03Njk0N0t6VCtjVG51NnpmdnNCNE8xd0xPNlg0bllX
            L1Y1Yy9FdHByQlI0Rk9UY0tTbG1CeVVlRkUxQUlJMjJKTUVmcVRyd1VsMndmQQpH
            WTRQK0tJRGhDLzYzY0hCWS9qZzBqYjN1ZlJHbkRqT0M2dEZ6WmtXL0NvCi0tLSBi
            bWdBVkx2OTlaNGxKdTc5LzRqcjU0R2RrV1E5d2NFNVk0amIra1pRL3I4CtgE8knD
            UvYV2kUetATc7ZfrGHhL1J0q5xGHbMkMKQK6h+vhLUeYVxfPkWjyZSCb62DCA6U1
            LHSkAk5yOWVrgBM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq18t5yaczngv0tw2809ycyhf2w2n4uj5yk9luyk4u3zfnnklylz2axxy4z3x9kzegtsc9s0xdlvaktsc0v5srrcmpev0yx6w2lwvgkyutnp7qfjadsps7g7uzzeak974465ej7dfk2pwfw7y98pljnlsh5puptqxm6zv2np92r92tz0f5mpz7hj604e2x8c0qu8vctgx8sexf2n2k502939fzzvzateztf3ykf58sxujzpkfqjq2eukdjgcrklr0t7n2vrvjzh6c5fqvn5fc4z8svcqm8m3yt8rqvhpf0zvy64wnvctq7urkff85ryd752s546pdk0390t6upnvhc80s5cvpf2je0ngyucxjffgucncwnsdrytgmmsrqwuzkkym27ygax356wzw0wmxvj8tsc63l4x5stzdmrcfne6w68v3gpvs76s37er0xr58rpxdws5e094x278lpzuclf3katssqvysg4hj6vh6av92pdxy63v0p8ghfw2m5m8zgmjsr385emek0q6suyyu4999nu68ql6wqj8ldp044zdz26qklx3kxeegplljufn0328qka9rwk44063yth02az0s4kyqqnzx07459qjqxljvjs9qyunnkppplkpvdcmey4yjfm4zsen9094pqgng0xve3qaewk29zzcf998jjde2alp2vj033datjexdm2nfqujyqr042pqasrjvvf2rujr4kg4kek49ww0h2fxxzshj79yzusprfljvgaf2eplh5n6cm2zvapt2r65v9xx7xfhyvj359fc9j7xw5g59zm62zhnjg3gkaj5z7959ss5nzn2uv9hkjnzz8nmqtt9csz7dgucnwapgdsya7zks0lt4rz0ywrddvwwzr9l0k6rk6uck4ydza9qqjr3m7gnldzg2y28ys0awtde0z462w93gechrx8zp7fyedhlupe98hz7gn6nt9zyhhgkkeh4njytwa64vcgc7334nhwepwajtqgp7gwv9nz3dme6z44hjzw9c9dxakzp8fyjfatk5p9g2dd06gef546afsc2tw74qvc2h272xe6n4qqpkx2xz8qt9fdx4qwfljxah4q6yhukjzfz2fehxrnsd9m29yu0hrr6d7u6h4qnpx2hwdsgjpecemvjpej55ej20f80kg37x096n9t6setpw5v6p0unw6p4z757wjyx6f833y0hhwd4q970559pc0me3lnu86eqwgpw2se8qudpxwyu22ujylwmzwxjhxpca4nphegm5tpht0gnkpsl8p5667kxqfph8lu4z7ccjx4h9smk93p7hdn4cd6g4gvscpdw5e8tu2utlxcrhustdqp6e34st3yt2fumu8f374he8wpgqnpks3w32x6qmhf6rxrqp2nzkj2v7kqsy6m5wrcnen24k086wcun7q3pkjn54jqqfjvnh3m63tumk7zffsxznhj9jztckxesdpjx690qkp67d7rfyxapyqnq3f6x26edcpqsxptrnzn4r5rxqszhnq7lmyd4uac59acz5v7rty86czvxns6wcy2reurxduepdqmh4fxdu2msqas4pxcgj46tprm964p5d2ennatzucwpxgx2z066qsjdv4prpdktz86uf0h3xk7q7u8y799lsju30ucprzmeedgdq2jpvx6z6sfry4xugeuyk545w4lcdh9m0lffql0mhfundw6xxgm4kwj7wpyed0vuqadkqmxc2xulmfd60xcrh8ss489mygp6mqax6ydal3k222r556lfxgvcndmvskuej7wrqsyzkjl0yxd8avvdaqymfk5fctsqxn8lsyzqyl9h6wdyuhvl4nmmzx2t9n0txu90pvhwvjcjam920psu4qd9zxfxztx7nqq03ucpsxfc9acxzda9j8hq6mlg25s8v7h00zjmqgwflu03p56pukkf
    lastmodified: "2026-09-27T14:32:28Z"
    mac: ENC[AES256_GCM,data:hALNFBWKicVUdQQ4+cPbp8Lc577A3zLCd6L7WD+dWl0GAm+63zAtWyhlxPFsz+HHoQ3Uz/rNCVKFwm9ihbqWHXjEvpwHJkX1N8n4g3G5ub3uKZlYKzPBxG6p9dvrmexIZkM1XmWRiudZKy5cFAlBm9UEm1Iqp1GphN6XZW8PUwU=,iv:v5HwStbnk36o6CIWYbtHpCoeIoY2rzZlBzr8C+mDr/Q=,tag:zl+6VtH7bMIx63p8ExdcnQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
