name: "Build and Push Let's Encrypt Container"

on:
  push:
    paths:
      - 'files/lets-encrypt/**'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with: 
          image: lets-encrypt
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./files/lets-encrypt/Containerfile

      - name: Login to GHCR
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: lets-encrypt
          tags: latest ${{ github.sha }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
