host_name: ENC[AES256_GCM,data:ZMRvmmhru+11,iv:1Jtl7YXT1lh8cPHF6VOtOpcQs0hbqdh13aCK5CZZpso=,tag:1dnx8x9K05T/Kv2HvMvMSQ==,type:str]
main_user: ENC[AES256_GCM,data:6bfBfw==,iv:SY58KC9S0VRBWaGByDrjGrEZm29rBqP6r2GS2e8c0aU=,tag:zN2uNJeZOq68SDp52MUuHA==,type:str]
ansible_user: ENC[AES256_GCM,data:gCrbZA==,iv:gexiU9t91BA+1s0mcE+pOZL+jSXduPNLof0RFljO4DQ=,tag:VEOykdjygqW8L1+4ZE+8sw==,type:str]
podman_userns: ENC[AES256_GCM,data:ZCjjQNRByVNVuw0=,iv:iDFOjOgob9X4en8WBtxP09AmMPbbRU4v79AjdS9+k4k=,tag:z0NF92g0u4rST9LirJV9mg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEE2ZWtBQXFI
            VDQxWVM0N0JNRHA2SDdTdjBsNjdLSmxYZTdHaWoxWUJYa3U5dmJ3VlNHeFZBZURT
            UEM0L1I4cEZRdnFzblBXSzNNcURHRnM0QUtob094cHZZVm1JV1dUdUt0a1NndVdi
            MGswemhhRWFYQ0d1bFVjYWVlb1gySmdmb09ZZFEvOG5CdW9sL3dVQ3JUOXJ2TEFu
            bkYxaDRzcjE0a2J4Tk9qNVBGMWdMeXBqTmdrS3lTMDNnUVZnaFpZVmY0bldNbWd0
            YU91aHY2ZW93b29xZ1JiYTN0QnZTQlpSWDhWYktJRXFNOStPazhUWXkxMzRFRnFB
            MkcxQzgybE14RzQwN0dRcUdkRnFVL3QyQnpzcjdRc2YrWEkrZVpnTEgwajFDT2RU
            bnV6Y0tWVWhwT2xWTm43MVJJczNWNDRidnEvOTE3eDFvNGNSVkRXVVJkUTdRaEZ0
            TjlWbzVMN0IyK1o2aTBiY0RTZ3BCSkNRWmszMkl0aDNHWU00d2ZrNm9EM2hsRkx0
            clZIYWp5RnlNT1htbEpKSnJmOGNoMVBaRjJtVU92aWdCY3NSZ1lpcDkyNlRGYzRY
            NGZ0ZnV4eDVsWkY1UHg0bVMzYzZvYTEwbkEyUTVZTWowd2wyRmJMbktXaVFkRndn
            T0tFSWVabjhFdEZ4Uk9hZERKYUhwWXljMFZ5Y2d6R1lZNXV5MnRxNU94RjJTRi9E
            TXlIMlFZQVUvRjFVa0pIcm10L3NOMFI0eFhVbzNyY1lkM1VmYXJJRWJLdTE5VzU1
            N2t1Q1Q2eHRTTkFBRXRVdmRNd3FVSFFNdjVLR2dyaEI2L2RXMlNTa1pHaTBQY0Ir
            LzE5SVlHOHRUNXU0YXkxQ2xKUU9nQktBcTYweDJ5dzdtQWZQK1E1TkpqYms2WDBT
            aUdVaWZPeGJSek0yWHAzQTZ4T3d0dml2eEMyOERoWkx3cFhJNzQ0d3ViS2N5d0pn
            dEg4NFRoNnNRUXVhend1SXJLdGc0dHdVdktMbVlBN1cvdThURzhaZlhiZThLOFgx
            SW1lSGE4T0NVcFFiNlBOUkM5RzB5SUNLaTV1Sy95VThJajNwYTlxL1dkc1drRmxx
            OGtWeUFZU3E0SWh6LzFtSUcxOEVOTnBKT09ZN1J5c0dDZnRuRGdHdDdvUExzNzU2
            SnVzZi9ySzR3aW1MQ3pjb2xnYmxjaDhDMmg0R3dVZHdPUFBvSlRoVGQzd2NFOThj
            T2RMSklyK01teTg2WjVrdDlINzc4WDJNaHlUR2UwMzR4WTNyaVhBcTFJd2JnN1pa
            Ulcwc1drZy9NVEFKSHRxQlVqUUw5UXkwaTVFSktqekZTV2hzZ08rM3VrbUdQNEJB
            Ym9pcTNRRXZ3TU5VNG0vVGRLMkVBZmhmWTM1L3BzWFF1cW54ak92L01zcDcxVGV5
            MytLZnJiTzBpY2ZBMjdqY0pKd3Z3TVFNVmFXY1lCV3UycEJCMWsvMTJ0dkY2MzF4
            WFNNNGp6SzhQK2dRTm9uSWJMdnE2cEh4Nlg1TzloZHdjQTV2VmlXQ005cmw5L2Fx
            c2kxYkVyT1dBdDhPb2NNZlF6Wm9HTXVzZ3ZWSWtFa3Z6ZEZZNXlsUUJHZ2tpUFpv
            aHZ0elRRMzltdHFwOVZFL0paL1FGY05ZTGo3TEZwTmN3alpxQXVTaDgrVmVTMGF6
            RW1HTkY5bk1idkZrSHliVmNPcG1IUklWQWtxbWRlT2FRdTBpejRLM0c4TFk4Skc2
            dFZ0NVU5dWVaRlZUTkNzMmxmSkI3U1lVRnozRHFnTE82ZytpeURJYjNKTzFyRlFE
            a2I0bklaMEFVMktETXNpZ0pZNTVjeGx0REtBU1pXdVB5ZDlMNi8vVHk0VFU3NENR
            ZmJyY1hDU212WmRmdW4vbVlIQmdBOEdRSWRncTlRTlBVWmJiWFd6MHd4OU4zOW4v
            S1J2b1cyTG1EVm14RHp0REtPeXZjTXlhU1VMR080eWV3NGNmYytFa0lNdXRQZwpF
            R2hydHkrcnFMU21ZUzJOeFMwU25kcG1ncVJKYU5QNjJ0WjF1eDlCZzNBCi0tLSBS
            SlBwK1FiL2xaaHQyR212djBkZTVRSUcwM0kreVkyaThvdFFlVTBqUUtRChSJOQZR
            TuK7G9TfMZc/Z+KtI6h9KD8BeQs80fFU8OQ/ZofNQpmYceUm20VrpRwt5CMO3plG
            L15Nz3HgT4tqnGs=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq18t5yaczngv0tw2809ycyhf2w2n4uj5yk9luyk4u3zfnnklylz2axxy4z3x9kzegtsc9s0xdlvaktsc0v5srrcmpev0yx6w2lwvgkyutnp7qfjadsps7g7uzzeak974465ej7dfk2pwfw7y98pljnlsh5puptqxm6zv2np92r92tz0f5mpz7hj604e2x8c0qu8vctgx8sexf2n2k502939fzzvzateztf3ykf58sxujzpkfqjq2eukdjgcrklr0t7n2vrvjzh6c5fqvn5fc4z8svcqm8m3yt8rqvhpf0zvy64wnvctq7urkff85ryd752s546pdk0390t6upnvhc80s5cvpf2je0ngyucxjffgucncwnsdrytgmmsrqwuzkkym27ygax356wzw0wmxvj8tsc63l4x5stzdmrcfne6w68v3gpvs76s37er0xr58rpxdws5e094x278lpzuclf3katssqvysg4hj6vh6av92pdxy63v0p8ghfw2m5m8zgmjsr385emek0q6suyyu4999nu68ql6wqj8ldp044zdz26qklx3kxeegplljufn0328qka9rwk44063yth02az0s4kyqqnzx07459qjqxljvjs9qyunnkppplkpvdcmey4yjfm4zsen9094pqgng0xve3qaewk29zzcf998jjde2alp2vj033datjexdm2nfqujyqr042pqasrjvvf2rujr4kg4kek49ww0h2fxxzshj79yzusprfljvgaf2eplh5n6cm2zvapt2r65v9xx7xfhyvj359fc9j7xw5g59zm62zhnjg3gkaj5z7959ss5nzn2uv9hkjnzz8nmqtt9csz7dgucnwapgdsya7zks0lt4rz0ywrddvwwzr9l0k6rk6uck4ydza9qqjr3m7gnldzg2y28ys0awtde0z462w93gechrx8zp7fyedhlupe98hz7gn6nt9zyhhgkkeh4njytwa64vcgc7334nhwepwajtqgp7gwv9nz3dme6z44hjzw9c9dxakzp8fyjfatk5p9g2dd06gef546afsc2tw74qvc2h272xe6n4qqpkx2xz8qt9fdx4qwfljxah4q6yhukjzfz2fehxrnsd9m29yu0hrr6d7u6h4qnpx2hwdsgjpecemvjpej55ej20f80kg37x096n9t6setpw5v6p0unw6p4z757wjyx6f833y0hhwd4q970559pc0me3lnu86eqwgpw2se8qudpxwyu22ujylwmzwxjhxpca4nphegm5tpht0gnkpsl8p5667kxqfph8lu4z7ccjx4h9smk93p7hdn4cd6g4gvscpdw5e8tu2utlxcrhustdqp6e34st3yt2fumu8f374he8wpgqnpks3w32x6qmhf6rxrqp2nzkj2v7kqsy6m5wrcnen24k086wcun7q3pkjn54jqqfjvnh3m63tumk7zffsxznhj9jztckxesdpjx690qkp67d7rfyxapyqnq3f6x26edcpqsxptrnzn4r5rxqszhnq7lmyd4uac59acz5v7rty86czvxns6wcy2reurxduepdqmh4fxdu2msqas4pxcgj46tprm964p5d2ennatzucwpxgx2z066qsjdv4prpdktz86uf0h3xk7q7u8y799lsju30ucprzmeedgdq2jpvx6z6sfry4xugeuyk545w4lcdh9m0lffql0mhfundw6xxgm4kwj7wpyed0vuqadkqmxc2xulmfd60xcrh8ss489mygp6mqax6ydal3k222r556lfxgvcndmvskuej7wrqsyzkjl0yxd8avvdaqymfk5fctsqxn8lsyzqyl9h6wdyuhvl4nmmzx2t9n0txu90pvhwvjcjam920psu4qd9zxfxztx7nqq03ucpsxfc9acxzda9j8hq6mlg25s8v7h00zjmqgwflu03p56pukkf
    lastmodified: "2026-10-04T10:15:35Z"
    mac: ENC[AES256_GCM,data:aKZHDG4jM1i4bc729U8rFntVDDQ48Zqad0UNx2zDnnNPJTyG4iZEGX4YE1fsuLJZt1Tqu/cNsRzHjg0ySmsWSGngzTkQ1JssJ4TRrT3H3h225i8k6CqGS6nZq9iJD3tL8xLSqCCjhNIIwsHYVuHdO9NgwlNI8nfkDAvmVNAeWSI=,iv:Ah5+AaML5TWZoWvup6wPD3HsLiNNQpynVFV6PSWL7Ig=,tag:sraqtso4uLj2Ooc9WMwl7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
