host_name: ENC[AES256_GCM,data:qEVOav655hVR,iv:volVl31DKX9rEvkf8RoThBeiO/LM26wGXURV2azqzZE=,tag:5qTaXsj9Tz+MLNXEpdgKWA==,type:str]
main_user: ENC[AES256_GCM,data:N2AnAg==,iv:yRDD1MpdQJ1k0NHfaQFo5GmNXbV+tVMYSLjhS5Lk/1c=,tag:m/oDpUpzU5BK6s+OC/i+7Q==,type:str]
ansible_user: ENC[AES256_GCM,data:VVbjZw==,iv:MW7gq+OpEL2XKq0uQvzx2AY2cxoD2uvVHI4j92mhGVg=,tag:ZDcl576rdTWAs53DY6BIBA==,type:str]
podman_userns: ENC[AES256_GCM,data:kP6xQMSlkwPBcqs=,iv:CI0ucMzeHypB33ZFg4DrCRmZRvWTyZA0q+x4x+R/0Kg=,tag:8DO5a4RtKiQJECHErrpg0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IERqUEJkUHJu
            RUR4UG1WUkdmc2QrTGN1Qm0wM1VGdGIxMXgwNS9yRlZUZkFPTDhGVnU5Qjlnc2dL
            L1oxOXA1Mmc4OWZyOTRVdHRRc21RNVZsK1FIYm04WTFiYTh6OVluV3EzU2JIUEtF
            TncvKzNDN0M4Ymc1bUNBT0VaVjh2SFg2cWo1UkxCb1RZQmtQTm5mWjd2U1cyV0pC
            U2JUMk9TYjVaR0RRLzJ6bVRVTlhMVmVTbXA1b0p2R3d4YTlYU0FVaDZpeWwyanFS
            TkUySUUwVzlZK2RkNjdSeDY2Ymt6VVhZSU44dFBHeWlqZEpqd3lFaW1wNUdtaGti
            dFFZVFNSOU8xN3JEajNhRE10RzJVaytSTUFmYThsUGVmOHpiWnFSS1RzYmgyb0Nu
            aEZzMVJuY2liUnk1bEtUcENuL1JmNThEUDNBTW11c0JNMGIyUUZOV0NtcFJoY1pa
            TEhWcHBVV1h1MFEveENlaVN6Tlk0N3BDMVp5eW5scTIyQW94b2lMd0JNa2tXV3Y5
            MFpkdG01QmpuMmJJb2g3TnpFcWlpL1dqYjZrUzZXQzJzdlhuZ2xldFpaaTA3NlFx
            OGFRcndnNDNYRHgweUd6NmFmZWhFdXR0WnpZeTVwWHV3VWFIS0VrY01saDBYdHVE
            SnFtemE2cHFrSjEzMU16SnoyZG5iaFZsRkF2Sk1mQTZqcHBhMWU4Wlh4b0xkeGdI
            Tkthem8wTVpsQ3QzZll4eS84dTNJcEd1Y2U1ckRvUmxCWm0yVTNyVHZJajVZMlcx
            S2UyZDRLTWdSNHB0UkRvU0s1bytoblQvN29UTjFjMUVtNDBQVWtiREY0VTdudGpQ
            UWdnd0o3N0tVWXYzdG1KSjhzMWRCakdjSmlIUytIdkFrMDM2WnJSQnlId1cwcXdF
            U1I1c0FlM0ttaTlSdXVLQmVKci9ablJrZWJzVm5jandUZVV3RlpEZUtMVFl5Q0Z4
            UklMZUpZV25SYU4zYU4zM0RuT0FuOGkwYTlFejB0UEdLSDZOY0E1bWltcDFiaHFx
            a1pkKytweGVyMUdLSUpNeDM0RVV1SDlYSjVNdkR3Q1FNRlJBazhzN0QxeHNxZUwv
            Tis1SlU1MGRBVFNDZ1p4WThGemlIWHhsK0Y4U2srSmt5MUJWQitMeEF5UnY2MUZp
            RUx1S2FmL3FyaWRKUHVNeWgraERKTmk5dTdrLzRXRGhWQmttc3JSSURzajFzRzI2
            RGg5OWl3NTI5M01ZTnVlR1Y2cHM5SGE2U1ZjV3JLMXVVQW9lMzF1TkswWWZrMjZa
            NWdyRjBMMDBYcmJ4Ym9yVW5aZ05EMDdmTDdLODE5aGl3WkcwNzdiZUtCUHVDMjla
            V2poa3NxRE11UHJCNCtMTXlzVzVqMnNiQjZBZnFLdmlDQXB5VnJkQnQ2N05vd0hM
            SVF4YTVlSzd5Q29NcTFHL0xuVHdNZFM2ZStvelhpRVM0QVd3LzZmOGZpMVEyQmlk
            QlBzZVluUlZpN21vSHNOemUwT2Y3cXMwajBMeTFUVjZVZ1J2MjF1TFpBRmZWK1VP
            Q0k0MTdhVjhxdUNNRE8yYSs1TU1TNGdGQ21Cb1hRc0J5RFBhUE5pN2wrd2Q4dHZj
            TkU0ZGRqUTZGSUhSbFB3c3ZOS05NVzNOWDZiVXNtc1JKaDl3dVpQbHZ0ZUZOYVBn
            cmNXVlU3K250V0NpSGY4VmxqN25ZenN3SmdoVjJZZWhOakQ3a0VsUStnL1R2THdh
            UWtxQ0I0Tm1ZMnFxNWFLOHhic0ZxbSt2ZWlkR3pxQnRJRWxOMnN3WDNReHZQeERR
            TWgwNDNYSERNekdkcU5IUDcwVUVobWEyWEtHQ3JZY01XWG1XelRBb293YXA0bHNE
            RG80OXozMEJuaGhBWU54QzE0bDJoNDcxWkNLeXdwN2tld25WcFdRc1FkWnJmaUxz
            ZjQ4MWhSenpabGpGUmlWU1h0MkNZajNnUWZUTXlDZTJSRi9ocEVPUVFBMk9TZwpx
            WDkySHcwUElrYWhERzJVNUV3cWRpdWc0Z2NyUWM0YzQrVktQbk5WWi8wCi0tLSBN
            eFkvSFR3QWt5bjQzMEZJWmxoZG1WSW80MHRXMG1rNXBETCtzOWxncVlvCjeK6EgP
            Y3jXdejo8P9uPtl38K/k4ihwZdeXDfRvu4UhRVdaj6TrsYW2fwzAqle9C7oF4Q5x
            zxVmjEjc0T0Lemo=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq18t5yaczngv0tw2809ycyhf2w2n4uj5yk9luyk4u3zfnnklylz2axxy4z3x9kzegtsc9s0xdlvaktsc0v5srrcmpev0yx6w2lwvgkyutnp7qfjadsps7g7uzzeak974465ej7dfk2pwfw7y98pljnlsh5puptqxm6zv2np92r92tz0f5mpz7hj604e2x8c0qu8vctgx8sexf2n2k502939fzzvzateztf3ykf58sxujzpkfqjq2eukdjgcrklr0t7n2vrvjzh6c5fqvn5fc4z8svcqm8m3yt8rqvhpf0zvy64wnvctq7urkff85ryd752s546pdk0390t6upnvhc80s5cvpf2je0ngyucxjffgucncwnsdrytgmmsrqwuzkkym27ygax356wzw0wmxvj8tsc63l4x5stzdmrcfne6w68v3gpvs76s37er0xr58rpxdws5e094x278lpzuclf3katssqvysg4hj6vh6av92pdxy63v0p8ghfw2m5m8zgmjsr385emek0q6suyyu4999nu68ql6wqj8ldp044zdz26qklx3kxeegplljufn0328qka9rwk44063yth02az0s4kyqqnzx07459qjqxljvjs9qyunnkppplkpvdcmey4yjfm4zsen9094pqgng0xve3qaewk29zzcf998jjde2alp2vj033datjexdm2nfqujyqr042pqasrjvvf2rujr4kg4kek49ww0h2fxxzshj79yzusprfljvgaf2eplh5n6cm2zvapt2r65v9xx7xfhyvj359fc9j7xw5g59zm62zhnjg3gkaj5z7959ss5nzn2uv9hkjnzz8nmqtt9csz7dgucnwapgdsya7zks0lt4rz0ywrddvwwzr9l0k6rk6uck4ydza9qqjr3m7gnldzg2y28ys0awtde0z462w93gechrx8zp7fyedhlupe98hz7gn6nt9zyhhgkkeh4njytwa64vcgc7334nhwepwajtqgp7gwv9nz3dme6z44hjzw9c9dxakzp8fyjfatk5p9g2dd06gef546afsc2tw74qvc2h272xe6n4qqpkx2xz8qt9fdx4qwfljxah4q6yhukjzfz2fehxrnsd9m29yu0hrr6d7u6h4qnpx2hwdsgjpecemvjpej55ej20f80kg37x096n9t6setpw5v6p0unw6p4z757wjyx6f833y0hhwd4q970559pc0me3lnu86eqwgpw2se8qudpxwyu22ujylwmzwxjhxpca4nphegm5tpht0gnkpsl8p5667kxqfph8lu4z7ccjx4h9smk93p7hdn4cd6g4gvscpdw5e8tu2utlxcrhustdqp6e34st3yt2fumu8f374he8wpgqnpks3w32x6qmhf6rxrqp2nzkj2v7kqsy6m5wrcnen24k086wcun7q3pkjn54jqqfjvnh3m63tumk7zffsxznhj9jztckxesdpjx690qkp67d7rfyxapyqnq3f6x26edcpqsxptrnzn4r5rxqszhnq7lmyd4uac59acz5v7rty86czvxns6wcy2reurxduepdqmh4fxdu2msqas4pxcgj46tprm964p5d2ennatzucwpxgx2z066qsjdv4prpdktz86uf0h3xk7q7u8y799lsju30ucprzmeedgdq2jpvx6z6sfry4xugeuyk545w4lcdh9m0lffql0mhfundw6xxgm4kwj7wpyed0vuqadkqmxc2xulmfd60xcrh8ss489mygp6mqax6ydal3k222r556lfxgvcndmvskuej7wrqsyzkjl0yxd8avvdaqymfk5fctsqxn8lsyzqyl9h6wdyuhvl4nmmzx2t9n0txu90pvhwvjcjam920psu4qd9zxfxztx7nqq03ucpsxfc9acxzda9j8hq6mlg25s8v7h00zjmqgwflu03p56pukkf
    lastmodified: "2026-09-27T14:32:31Z"
    mac: ENC[AES256_GCM,data:T4ZkIE0WK5nZ6dA7D87lKks7G1P4SkCJS4A69UrzCUy8lOavV1jZ+qEJ+zWlvzHDyZMzRNRYplvdLK9quyHWkKX3qLG9k6IULI9V4G0TzTzu7my4JQHEcCivNkJckUImsZxBZYC7c8MjMYaW52Ekz1+2KmmZFjlXJIiy3ZDkUA4=,iv:JEhmDcfHMvxv8twReJKGI24Mo/Ui0zD4CSEB1vQV56w=,tag:Y8QHdlyphoOTaY8TKh21zw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
