host_name: ENC[AES256_GCM,data:ATY2ev7Y,iv:9lyF6Mn26y/PzZzXHstvDyhm6ouJ82uqg2uDXFLfwt4=,tag:6iYUTvbrC0RIlJzQFZPveQ==,type:str]
main_user: ENC[AES256_GCM,data:1Zko0A==,iv:mghn41DwglIDRBop3FffZROrHi/37TclubFH44HcweU=,tag:neq6AiwRG5J3KIjlqcnqjg==,type:str]
ansible_user: ENC[AES256_GCM,data:vUCCMw==,iv:J7dO7axfths5L2BwDBrhuDupjY5WrsPUuTYsRqw06Zo=,tag:NrA4rPRgsAHNzl/8BXBt9w==,type:str]
podman_userns: ENC[AES256_GCM,data:4sppFvAquwdWe2WaetU=,iv:pSd1DqRzq2UH7qdA29yAzCfPBeHpNeKWfP7RWnfTIWM=,tag:W73s83hkrdDTM2+DqBRq9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEhrc0lZY281
            dTIzb3IxenhRL1NiRTBpRktldEN2UnVkUlo3Z0dRTXUycFJqV0R0TWRwL09aVWhS
            dzFNa2Q2ZTR3b1M1K1k5WEZ0akJwdE1Xdzk0My92d3oxQzlpUUR2UU1Oa3pRc3F6
            TkNQSTM0Y2hpUW9vYXFLekF4QTEyUWtKU1NjODRpcStIUUVoQVJhS01XTnJreFQz
            K2dvMm1zZG9KODlzZ3l3WlU0QVN0ODhZTkdGTVlHbE9XRVRHdXRvZndVSG1pTVZQ
            VVV3c1BtR0JCajYwVnB4ODBKT3NWRWgrdlRPT2V5RW5MY0h4UnN1VnhXcXg5bGMx
            dlR2VUd2NnNLaEdya05QOWlKeVVleDhzSnZvM2ZzUWtBbnR2NW45UWloYXNLd1Q0
            OW1scWZWUDRybHN6dml5blFsNTFLQWlhVC9HSkM0OUJXOTBPelU5ZGV0YXVhNDQ1
            N3FpV25ZWmtkY1hKd0xMZDNaRUhta00ycEZIN3ZkcHJtZS9aeG1NZ3Q2c2ZLYlhy
            dlpaYk1pQXkrZ2NWZzdHOVdYOTNMZXlpb0VOTFAzZXdOTWV3eW8zcVJYNktOUnc0
            VjhZZ29rbEYxYlBSZGhJRmpsUmJLdjFkMUU1UlBWdU96aW5SUzRZcDFrcldQalc0
            QXNkeUR6emxmR0J3c0FkdktnL3BLUmtSRnRNTFc4bk1NWlJzTkdONEpGSkl1UGZZ
            WVlEaGtSYUh4c0lta2dZOFNiK2VKZThGMDlrRUN2VFBRMkhFc3Q5MVlxU2Y5YVcz
            eHJERTM3Vkw0RG5KRWR4dDBIV3JYRlF3NVBtcGZxMlVVeVBtTmRyQVNTTk1TbjRu
            Z1dPRWpTVnBvSG5KMGk5SHBkTUdGOHQ4cWVLQzNPa2ZuMXlQUG9JblRXZzg3N1ls
            aE9vd25sOEs3aTN5cUN4bUw0RVovY3E5dE9qc2VOWFNzVXVia0xKK1p1MDBFTGFt
            dmt3QjE4T21INkd6K2dOZGkxMSs5WXdFU2JrOTBJVU5ITE1pbml0Ylg3bnA3dGlu
            d3lPZ2JoUUNyWVhJZVM2em5zenBsNXpzdllUdHJobXBsd3JYNExxYXlnU2crYkxM
            cVloNFFPZGZQbFhuUW1wSHRsVXNDLytMSW1DM2VxRTNTanEvTE5nSUM2SHhEc0s4
            Mnh4RlY1QkgxT0F2SjRzSEFEZDF5QkhCeDVYUEhuVGpVamx0bFR1MlhxNlZhc1FV
            NzgxN0lGMzF6OGgxOVhhOTRsZ200MTNDWEJTVE14MGNncjk5ZThZdGlSMHlmOW5v
            VXc5WTFSVXQ5cHo2SXk4TmFZY3RrZ3ZmQ0RJUW1hNEVBblI0cVltZ2hXSittdlgy
            UzB5bnpGdm1UN3JRLzQxK1BnVW1KeFc2N0RWWUxZQzN4OExtblRvVXNtcUtmeSto
            cU9KUm5EM1daYzg1TkVZaGNaSk44YUJUTTU0WjZSMFpyNysrUVhGNkp0WWErM1cv
            cGxXN3lhVlRjYjdoRFhFbmNhYUN5YjdhVXNYMEhTckNpNDFkbTNVdWt0K3B0cXlz
            MjRWbjI1MTFuVDVmcVpJbXVPRXh5UUE3TnFZYkVBRWkyRTVnNWEzUmVmMm12MlBp
            bFNObDU2d2VvOC9RUWlxQmVSa2I2UFh6MnVlWUtsaGNmdHlMWEVzR1VaZWJlREtQ
            ZExXTEFlNHRxOUJzTkh2QnJPYUJ2VHZ5cTRBa0VqMnNwb01RTWhVN3lOZHFDNG12
            cWpoRG1pMWJ1dUo3YWFKYndVd1dVZlJjQXBENDFMeHJNWTBqdythd2J6eUY3U1gy
            bHF3KzlsSzB2d2o1NkZiOWJrNmlRSjBlblNQeFZUQUo2WXlESDF3VE4ra29Uc0Zp
            b1dqdXRqMmNhVFVKdnpORXNrYUFtNERkRFA3RzRpTXVlbkllK2VGRDNqZVlEa1hl
            OUN5UlhrNjg5YzV0b1plMXl6eFhsTmRZd2JoalZ1Sjg4VU1UQUs0T1JtaEFWdwpk
            eklxMm0xRWxZZi9XT2NRR0c5UG5paVRMOVVIS0FiWllGdWtVSGZrR2dzCi0tLSBx
            UU5CMjBUellZeEo5T2ZHQ215YWdPTk1yNlNiQjN4OUt1NkVYOURwbWJRCv302YrT
            CFc2WnmSZW+tkCA87+p+NGj2XpLJ1ysud0qyrFW7/E0kyWHIS6ypTtelk+/WTBTW
            MUkzgYuriBRNLpM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq18t5yaczngv0tw2809ycyhf2w2n4uj5yk9luyk4u3zfnnklylz2axxy4z3x9kzegtsc9s0xdlvaktsc0v5srrcmpev0yx6w2lwvgkyutnp7qfjadsps7g7uzzeak974465ej7dfk2pwfw7y98pljnlsh5puptqxm6zv2np92r92tz0f5mpz7hj604e2x8c0qu8vctgx8sexf2n2k502939fzzvzateztf3ykf58sxujzpkfqjq2eukdjgcrklr0t7n2vrvjzh6c5fqvn5fc4z8svcqm8m3yt8rqvhpf0zvy64wnvctq7urkff85ryd752s546pdk0390t6upnvhc80s5cvpf2je0ngyucxjffgucncwnsdrytgmmsrqwuzkkym27ygax356wzw0wmxvj8tsc63l4x5stzdmrcfne6w68v3gpvs76s37er0xr58rpxdws5e094x278lpzuclf3katssqvysg4hj6vh6av92pdxy63v0p8ghfw2m5m8zgmjsr385emek0q6suyyu4999nu68ql6wqj8ldp044zdz26qklx3kxeegplljufn0328qka9rwk44063yth02az0s4kyqqnzx07459qjqxljvjs9qyunnkppplkpvdcmey4yjfm4zsen9094pqgng0xve3qaewk29zzcf998jjde2alp2vj033datjexdm2nfqujyqr042pqasrjvvf2rujr4kg4kek49ww0h2fxxzshj79yzusprfljvgaf2eplh5n6cm2zvapt2r65v9xx7xfhyvj359fc9j7xw5g59zm62zhnjg3gkaj5z7959ss5nzn2uv9hkjnzz8nmqtt9csz7dgucnwapgdsya7zks0lt4rz0ywrddvwwzr9l0k6rk6uck4ydza9qqjr3m7gnldzg2y28ys0awtde0z462w93gechrx8zp7fyedhlupe98hz7gn6nt9zyhhgkkeh4njytwa64vcgc7334nhwepwajtqgp7gwv9nz3dme6z44hjzw9c9dxakzp8fyjfatk5p9g2dd06gef546afsc2tw74qvc2h272xe6n4qqpkx2xz8qt9fdx4qwfljxah4q6yhukjzfz2fehxrnsd9m29yu0hrr6d7u6h4qnpx2hwdsgjpecemvjpej55ej20f80kg37x096n9t6setpw5v6p0unw6p4z757wjyx6f833y0hhwd4q970559pc0me3lnu86eqwgpw2se8qudpxwyu22ujylwmzwxjhxpca4nphegm5tpht0gnkpsl8p5667kxqfph8lu4z7ccjx4h9smk93p7hdn4cd6g4gvscpdw5e8tu2utlxcrhustdqp6e34st3yt2fumu8f374he8wpgqnpks3w32x6qmhf6rxrqp2nzkj2v7kqsy6m5wrcnen24k086wcun7q3pkjn54jqqfjvnh3m63tumk7zffsxznhj9jztckxesdpjx690qkp67d7rfyxapyqnq3f6x26edcpqsxptrnzn4r5rxqszhnq7lmyd4uac59acz5v7rty86czvxns6wcy2reurxduepdqmh4fxdu2msqas4pxcgj46tprm964p5d2ennatzucwpxgx2z066qsjdv4prpdktz86uf0h3xk7q7u8y799lsju30ucprzmeedgdq2jpvx6z6sfry4xugeuyk545w4lcdh9m0lffql0mhfundw6xxgm4kwj7wpyed0vuqadkqmxc2xulmfd60xcrh8ss489mygp6mqax6ydal3k222r556lfxgvcndmvskuej7wrqsyzkjl0yxd8avvdaqymfk5fctsqxn8lsyzqyl9h6wdyuhvl4nmmzx2t9n0txu90pvhwvjcjam920psu4qd9zxfxztx7nqq03ucpsxfc9acxzda9j8hq6mlg25s8v7h00zjmqgwflu03p56pukkf
    lastmodified: "2026-10-04T10:15:34Z"
    mac: ENC[AES256_GCM,data:ap5rdwDMGl+h2JnEJcWCDaUXQxVCwWBh3Y9UD9qyIHZQbbYw1rHFIGMR6LV/2CLF3D19arrj3QLXatv5BeFP2K/KXWfpk5YoHoIsp7v5bJ1hraaptBctH090ah2e5eqP+rnuOGmfXzvi8zUNJ/YMsqJM72jdiveg+BUdMsOxhLg=,iv:vxKE82S47JRWRzC5g9YTbyF98FN9iTHgsl6i6C8FoTs=,tag:e+GMntZa2du9tNvlNnMbFA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
