host_name: ENC[AES256_GCM,data:Ni+IUTTb,iv:xjwovRr1FLHSAtem4UsStvlZwUqD0IDtV9nSBxrY3hg=,tag:/3/7OODstEDYi9+C9fpmnQ==,type:str]
main_user: ENC[AES256_GCM,data:z/4JyQ==,iv:WksJ/GJQDjE6XyZisjCyqNXRntbI/NxZkhz+gopo3/o=,tag:pXmkrz9+fa/TDDhc6z1HeQ==,type:str]
ansible_user: ENC[AES256_GCM,data:DSwIhQ==,iv:t1m8egbHhMYNhYnaSBj4LREcXIdTXLVf8U/diUWMWK0=,tag:xuecoOy90z5WxU0cd/Q2LA==,type:str]
podman_userns: ENC[AES256_GCM,data:Ndfu0f2xrunz+QOwRyM=,iv:o5dYIIYVcWOtEHuIi59yOXKQK87dO5w8nyDLBeFfrn8=,tag:EzjpGeIMizmpPJEh5yGO8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHZnSGM3Y3hv
            Q0pZeWliZk1nRkFYd0hITG0xdFJKTzVTU0VyM01WWmpGMkFxQ0p5S1A1eFlKY1p6
            RjB5Q2lrUG1YNVI0MmJIU21qS1JTeHkyWkNsMU55MTY4UzVQZW02ZWUzSnJQbWNO
            YmpISnlBakNzdTNObXVaYnR5ZWI2a04xUUtEWDRaZWgwaVMrSUh0WGxRUjAzUnJV
            RWVUTzhIdnpxZVdwbmlEYW1PWHoxREVYY1RUb2pjcnd2a1R3WXBqL3IrSVRkTUU0
            UTdVd0JLOVpUNWJYUHFoUGpKd1UvbEp0MHNmMnc0SitlVnBkQ3FBVkpyQitFN2l2
            MnpBREtyWStoOHRqcXk0ejVIYWgwNHNvNVUvY0J2eTFZVXA1aUF6TG9TTG13MmF2
            QkZvQlZmeVdybFg3U3ZZbG5yMWxuSjRrZWlHVlh2NWE0KzZ2R2wxUG13eTc0WlBv
            M2N0R3ltRytnS21jZHN0cG9uODh3T3pVallCZkNCVk0rU2hnT29DOW5WQTdKenc1
            NktUbEh5cEo0ejg4QTVNR3dHZXc0U0w5ejJLZVo5by9XaGdlNU9BWG9qMkdleTVs
            QVpHbHdZSkNXcU50aUdnZmhtRzdEbkx3eXkrK3lWYXhBd2RPQThwempqa1U1eDVR
            WXlmaXF1L1RhSTA5bXlvS0VxSytyS3gwT2FkbmxWYnVZMkdzTythWVdhTGhQcmtw
            bE1iTTd3dVM0ejJPd2JFdENYNXV6Q3BVL1hISVBrMWlOV1MyaUdCZ3o2eXR3blk5
            TW1OSW1LRnFyb21qelM2U2FwOThOYlBWQ3lYSS9Ka3dpTFh4dkZ3SEpiRlNObnVv
            ZW1pNXpNa3BmMHdjenFGZmxDV3M4a0RlSE5rMGo0em4yaVVOZmI3dE1TZ25pRXNG
            b0MzMzM5TlVQTTN4OFZ2TlRYaStxMEpLenJkbGZOSkVHRzYvbjNRVmJSdWlUQ3Y2
            dHdoNDUzRWt1UzR3WnBRNmFSbGs1T2hqbGIreGJoYUtKWnhaMEVhbWNPeTk0ZVdV
            RTJxbWtWQmpRNlBDbXBIV28vZ3VTL1NDTXZUN3FXYWRpMXo3aUhqelVsTklzOVUy
            SUFCQitNMG1iYkh4V1Z1ZXcwOXFkaDlnY3NyQVNVd2pHREFvZGYyRWV5eHJwZXg5
            aDROeTdENVh2MVBuUTdOdEE2enduT2t5cGVVbktVK1J2ZVU5MUJRMTYwcUhEVVNs
            YlpIR25VL1NPRmlyODJzZDFnd085anpQT1RudFlrRFo5T0V4YTRKZEMzZFJ3LzVR
            RXV5empzcHlqNDhRdCtSbDl6STAzQjZHN0c3UUlETVlodm8xMW1kOHVKSGtlZWwr
            M2g1YnVpL3FIbm9UUjBJQ1lIL2lta1hhVE00U041TnhleDhxRDJ0UklJTDZ2NE8y
            cm9Sdmovd2lpM0FKVnJvUkVZT3l6OE1tREhaU3NVM0srd1NtSmZVa2NRYjVqZXVw
            aWRuWURiQUwxN0Y5YUpRRU5qVEd6ekZtYnNwSDJVZUYrbkdXSVY5VHl4aytibHU1
            K3FxWkRlRk42WGR6OGVzcVkwVHdycU56S05pTWtXUTEvMEptVng0d1RpTG94TU94
            ZFlSSm1mOWlmZ05ubWpKbmlBSW82SVlCNWtlaW5iR0JXUVRpNkJTaUtNdVI4QXVr
            MGY3Zm5EZE4rc2V6cVQrUmkrRXd5WmtUTHBlSEJkbWl0S29xaVlIRnlSV3pYbURR
            RktYTGJoT2thaVErTEhmQmQzZFg4TURRSUEySFNvWDVxdzFqT3RrWXZSS2lKdjRn
            akJwKzBSTiszcEFRT09zM2lPRmIzWGR3L1kyY0ZZS0NBVWkvN1dhUVpPWDFxSHE2
            eksyZW5vV3dGNUc4ZWpKR0U0b2x1ck12cnUzeWN4V0ZEQTdXeXJtVlZxR3NXeFR6
            REo5U0o3alYrOXVlUUFGV3IwcVZGWGZtYWp1aWJIMGwwNTIwVXZCaE9Ga2FHZwpU
            b1Z5ajBhbWhRU1VVVU43NTRJZlhkbVhNSCtHOU91U2Ewb09BQXNwZnBnCi0tLSBz
            UEZwbGw3Z0o5OE5jck40eHE5cXJNOWVsbGdFSnZKeEtkKzl1eXROTU4wCjTFWqjl
            3q/LQbf3W6/8+yBNM5t+GdO+fHWiY6tQwaFsQ77+wIOeHiSe/pDeA52S8kZz4vi5
            s1cekxNdGxiMGxU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq18t5yaczngv0tw2809ycyhf2w2n4uj5yk9luyk4u3zfnnklylz2axxy4z3x9kzegtsc9s0xdlvaktsc0v5srrcmpev0yx6w2lwvgkyutnp7qfjadsps7g7uzzeak974465ej7dfk2pwfw7y98pljnlsh5puptqxm6zv2np92r92tz0f5mpz7hj604e2x8c0qu8vctgx8sexf2n2k502939fzzvzateztf3ykf58sxujzpkfqjq2eukdjgcrklr0t7n2vrvjzh6c5fqvn5fc4z8svcqm8m3yt8rqvhpf0zvy64wnvctq7urkff85ryd752s546pdk0390t6upnvhc80s5cvpf2je0ngyucxjffgucncwnsdrytgmmsrqwuzkkym27ygax356wzw0wmxvj8tsc63l4x5stzdmrcfne6w68v3gpvs76s37er0xr58rpxdws5e094x278lpzuclf3katssqvysg4hj6vh6av92pdxy63v0p8ghfw2m5m8zgmjsr385emek0q6suyyu4999nu68ql6wqj8ldp044zdz26qklx3kxeegplljufn0328qka9rwk44063yth02az0s4kyqqnzx07459qjqxljvjs9qyunnkppplkpvdcmey4yjfm4zsen9094pqgng0xve3qaewk29zzcf998jjde2alp2vj033datjexdm2nfqujyqr042pqasrjvvf2rujr4kg4kek49ww0h2fxxzshj79yzusprfljvgaf2eplh5n6cm2zvapt2r65v9xx7xfhyvj359fc9j7xw5g59zm62zhnjg3gkaj5z7959ss5nzn2uv9hkjnzz8nmqtt9csz7dgucnwapgdsya7zks0lt4rz0ywrddvwwzr9l0k6rk6uck4ydza9qqjr3m7gnldzg2y28ys0awtde0z462w93gechrx8zp7fyedhlupe98hz7gn6nt9zyhhgkkeh4njytwa64vcgc7334nhwepwajtqgp7gwv9nz3dme6z44hjzw9c9dxakzp8fyjfatk5p9g2dd06gef546afsc2tw74qvc2h272xe6n4qqpkx2xz8qt9fdx4qwfljxah4q6yhukjzfz2fehxrnsd9m29yu0hrr6d7u6h4qnpx2hwdsgjpecemvjpej55ej20f80kg37x096n9t6setpw5v6p0unw6p4z757wjyx6f833y0hhwd4q970559pc0me3lnu86eqwgpw2se8qudpxwyu22ujylwmzwxjhxpca4nphegm5tpht0gnkpsl8p5667kxqfph8lu4z7ccjx4h9smk93p7hdn4cd6g4gvscpdw5e8tu2utlxcrhustdqp6e34st3yt2fumu8f374he8wpgqnpks3w32x6qmhf6rxrqp2nzkj2v7kqsy6m5wrcnen24k086wcun7q3pkjn54jqqfjvnh3m63tumk7zffsxznhj9jztckxesdpjx690qkp67d7rfyxapyqnq3f6x26edcpqsxptrnzn4r5rxqszhnq7lmyd4uac59acz5v7rty86czvxns6wcy2reurxduepdqmh4fxdu2msqas4pxcgj46tprm964p5d2ennatzucwpxgx2z066qsjdv4prpdktz86uf0h3xk7q7u8y799lsju30ucprzmeedgdq2jpvx6z6sfry4xugeuyk545w4lcdh9m0lffql0mhfundw6xxgm4kwj7wpyed0vuqadkqmxc2xulmfd60xcrh8ss489mygp6mqax6ydal3k222r556lfxgvcndmvskuej7wrqsyzkjl0yxd8avvdaqymfk5fctsqxn8lsyzqyl9h6wdyuhvl4nmmzx2t9n0txu90pvhwvjcjam920psu4qd9zxfxztx7nqq03ucpsxfc9acxzda9j8hq6mlg25s8v7h00zjmqgwflu03p56pukkf
    lastmodified: "2026-09-27T14:32:28Z"
    mac: ENC[AES256_GCM,data:K1eF0/T/HAIWf2cApe240dQ4V4dP9Z44ReBZb/+8Ddx5WxnFTiSaqAP2GZrUoO1VkyBXb3QbUuc9Jz9+wYVrlNON9hfVXGXHjX0WvtdhpKcsQFbVFJd9Jc/60evjZMouKEBBmRDkPFcR9uGPcBMg0iPh5p7ZkmBBsoYXcxjxY/w=,iv:C8Jmmkl2P0vQInWmqmjc3Xxbh+bNLQDZylGshjdmANQ=,tag:EZ5gpzUNN//rv6khOp0pDA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
