config:
  core.https_address: :13512
networks:
  - config:
    description: ""
    name: incusbr0
    type: bridge
    project: default
storage_pools:
  - config:
      source: /var/lib/incus/storage-pools/default
      volatile.initial_source: /var/lib/incus/storage-pools/default
    description: ""
    name: default
    driver: btrfs
storage_volumes: []
profiles:
  - config: {}
    description: Default Incus profile
    devices:
      eth0:
        name: eth0
        network: incusbr0
        type: nic
      root:
        path: /
        pool: default
        type: disk
    name: default
    project: ""
projects:
  - config:
      features.images: "true"
      features.networks: "true"
      features.networks.zones: "true"
      features.profiles: "true"
      features.storage.buckets: "true"
      features.storage.volumes: "true"
    description: Default Incus project
    name: default
certificates: []
