config:
  core.https_address: {{ {{ inventory_hostname }} }}:13512
networks:
  - config:
      ipv4.address: 10.15.103.1/24
      ipv4.nat: "true"
      ipv6.address: fd42:b5a1:ea0d:c322::1/64
      ipv6.nat: "true"
    description: ""
    name: incusbr0
    type: bridge
    project: default
storage_pools:
  - config:
      source: /var/lib/incus/storage-pools/default
      volatile.initial_source: /var/lib/incus/storage-pools/default
    description: ""
    name: default
    driver: btrfs
storage_volumes: []
profiles:
  - config: {}
    description: Default Incus profile
    devices:
      eth0:
        name: eth0
        network: incusbr0
        type: nic
      root:
        path: /
        pool: default0
        type: disk
    name: default
    project: ""
projects:
  - config:
      features.images: "true"
      features.networks: "true"
      features.networks.zones: "true"
      features.profiles: "true"
      features.storage.buckets: "true"
      features.storage.volumes: "true"
    description: Default Incus project
    name: default
certificates: []
