all:
  children:
    wyse01:
      hosts:
        wyse01.tailnet-ba52.ts.net:
    wyse03:
      hosts:
        wyse03.tailnet-ba52.ts.net:
    coreos:
      hosts:
        wyse01.tailnet-ba52.ts.net:
        wyse03.tailnet-ba52.ts.net:
#        wyse0[1:3].tailnet-ba52.ts.net:
#        nuc02.tailnet-ba52.ts.net:
    dnf:
      children:
        el9:
          hosts:
            marek246.tailnet-ba52.ts.net:
        fedora:
          hosts:
    desktop:
      hosts:
        fedora-kde-xps.tailnet-ba52.ts.net:
