all:
  children:
    coreos:
      hosts:
        wyse0[1:2].tailnet-ba52.ts.net:
        fedora-kde-xps.tailnet-ba52.ts.net:
    dnf:
      children:
        el9:
          hosts:
            marek246.tailnet-ba52.ts.net:
        fedora:
          hosts:
    desktop:
      hosts:
        fedora-kde-xps.tailnet-ba52.ts.net:
    test:
      hosts:
        192.168.8.168:
