all:
  children:
    coreos:
      hosts:
        wyse0[1:3].tailnet-ba52.ts.net:
    dnf:
      children:
        el9:
          hosts:
            marek246.tailnet-ba52.ts.net:
        fedora:
          hosts:
    desktop:
      hosts:
        fedora-kde-xps.tailnet-ba52.ts.net:
