host_name: ENC[AES256_GCM,data:bD4xs+6M8Rc=,iv:9YcDXTOuGaeYJ2kT8QH1AbEkF2PiHlXu/Y2+2oELYo0=,tag:tgXP7CL9inNxeqEvVISWbQ==,type:str]
main_user: ENC[AES256_GCM,data:nyfCow==,iv:S5MQaaHh0rMfE4pk2iftebZTGosT/tDxPZe5+TRpg/c=,tag:0fhHuRDuR0qX439YZWuncw==,type:str]
ansible_user: ENC[AES256_GCM,data:2PUwug==,iv:kZRLfuMm/ziV2R/k6t6j6BtQD609up7qpNWdF8GwEPc=,tag:dKxPRPUgFLKruLW+b4zSig==,type:str]
podman_userns: ENC[AES256_GCM,data:oHV9uIznJw/KZBM=,iv:NPJGncHDcyojZ7TQSOdIvBIMH2O/bOZyzVIg2vISscY=,tag:uDOfKnSc2SnAWlFo5YyMFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHIreisvOU1O
            N3B1bXlwWjVWdk9GTDZnYTNyVVBHbXBoczF0U3BxcG96QXhEaEFJZGlReHZubG5q
            Q1BsSzkyRmMwWENacnlFTGQweDhJc1ZQN3Byb0RhKy9uMHRZcDIxUXF3UDlaODBS
            bEFEZHY5RjMrSTloaHNzenhockNyOEt4UUdhKzQvU2JERyt4OEdZZmpRYUwyK1kv
            b0FqcHRWa0l1b2xHTGowTjJQalRFSU9DNkFVTUNIaFF0b1RCRjM5aCtjbjNZTTNH
            dnZIaUJCcDNRSk85R1Fjd00rVFVpWmNpaHlHMzBGdFVhMGltTzNZcjBWOE5pQkRO
            ZDZsTWY3WUVYYzY1R1VpMnB1TW1uQjBVc1NLZXphZVJHcjlOR3BQYUFTaDZCZ1Rm
            WmVPaVhKNnFjRXlhM2VMWE4rVDdPUllsNXFZQ3hxNVF3dDFXWTdybUNmZkxtTnE1
            bjFOMFRaYzdnL05HV25ZOW9xby9uNUtvOVpaZnNieEJaT1p5cmJvZ3dCc21mMmdH
            dSt5aVlSbTNwSS9oOVRDdXkwNk42d0h5WXlvRUhjcUw0VHkwMUlEWVUwL055TXhu
            SUlna2VnSWNiRDV5M1RZTFBYUEVmaUJIcU9TV0FIaTd4NXB3MmlLZGplTnJaVm1C
            YmtXTVBHNkU1UUdxY2ZkUjdVQVBnK3Y1MlNTWURCMlJ2TGh6OW1xVEpHQUExWUNs
            SFhFcXpvVGJHUDE3bzBsZnJraEgxV3dHbWw3dDRkY2dwei9jaW1OYUwxZGYyYi8r
            TmpFeVZPVlErN3Y1T3QzTSt3b1B5S3RhL05vOUdNU3Z3Yk55NjNwODdVQzFka3dm
            d3B0dkRMbHpzVWp2Q0NJWGt3bmFQQ1RXVjVjVTlsL2M3TEVab1JsWFRwQnhhZVFL
            Z0ViVlJIMWhHQ0NackZObElvdDU3S1BlbnUyWGNIR3JMaGp4VGFlT252WjFiZS9k
            Yk1iSVROaENoaU9remRMQ0tqQm1yVnRFYjBYeUVHeUhkbFcyUWJVTk8xdlcrOGd6
            dDFpNmcveGFNQ1FRU1NDbi9iV2FuRVNRRC9rL25HY0lwV0V0aVNhQjA4aDZSMHBI
            cC8rYXptekxsNXpPKzJwWFdOOEx1SzEwQmEyVEhMblJVRHZQYzg0OVAxSlF2T3lB
            QXUwQzQ4VXI0bGw3QlF6cmJ0bVorMlpWQ0MwZzYyaE0zbmdWUTBraWY4eC9tZzdy
            M0ZYZmQ5OElIMFdya0NWTUlQK3FCNUI0OHpHd0RRK0pBRUUvSnFkR3cvUWw3dVBr
            UjA1Z3NiSWJEeThwNnJ2VDQ3cENTaVVvWHJQR2ZDMDZ6UWtwc0c5TzVOMFJpUm5U
            aGpxVnM4UFdVZDkrR29FT0I3VFFHYnNLcnA0eVlDc3NXaExIc2pFdDhjMmhUL1B5
            THo5Y1VNaTlpb1FFUk56MTdBRkkyK3NtaDh1ZXE4eWJBbW1EVkVzdFlkb3FZTDJH
            RzRRSzBqc1BtV3lSa1E2U0ttbUNzTjRPR1Q0QlRpNFRjWldMNW5qcndremV4bXNj
            NitMZ0NTb1hodFF6MUpvSGtrOUJPeWVER0JsMWRubFprNlhYNG9UUnVScFBxRGdy
            YzdRTk1uSnkySnFEK0Y1Mnk0UXdxTGM3WVo5amFSclRQSmpNM2Vsd0x3N2ZQU3Jw
            eFROdmN0MThYSERrUTRXa2I1c2h1dzlJSk1tVitRdWVzc015U2lZK1U1d1FKUTlm
            d0RlK2c3YVU3NnZnUkw3bmdGaDh4cUZncCtkLzRKNFE0cU1XTklWeWtKcTluRzJu
            c25ZL0lGakNjbFY4eWp6ZDQ4NG1ZSmVTbm15Y1NRcEJvK3pmNkFvRTJWQnFsZkt4
            aFVweFJZVWUvTjhyd090aVJsVCsvcld0aTVCeG44Q3ZZVXFWM3dOako0TEVCZ0VN
            MTcvQlo1cjE4T1VJaXE0UTJjV21pOGlDVW5qL1ozbW9XbGVLd2YvVlZYUlFGZwpi
            ZlFHTjRpRVpnblVVSmd5MVdxMmJySy92NEV1NmxlckdRZWhOTnBpdC9BCi0tLSBT
            TmY0OEpqaExBV25pcjRSZ0hlZXE1YzFGeldvQnlyV0d4bTQ5SnJEbGRJCjeddY7I
            2s0fH/WFD1nBdJSWF6bt7l67/I/+bCvcBCEnKI2Am4vfG7dpOjXRN00trkPM/38c
            QmxP7wyNRHOO25k=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq18t5yaczngv0tw2809ycyhf2w2n4uj5yk9luyk4u3zfnnklylz2axxy4z3x9kzegtsc9s0xdlvaktsc0v5srrcmpev0yx6w2lwvgkyutnp7qfjadsps7g7uzzeak974465ej7dfk2pwfw7y98pljnlsh5puptqxm6zv2np92r92tz0f5mpz7hj604e2x8c0qu8vctgx8sexf2n2k502939fzzvzateztf3ykf58sxujzpkfqjq2eukdjgcrklr0t7n2vrvjzh6c5fqvn5fc4z8svcqm8m3yt8rqvhpf0zvy64wnvctq7urkff85ryd752s546pdk0390t6upnvhc80s5cvpf2je0ngyucxjffgucncwnsdrytgmmsrqwuzkkym27ygax356wzw0wmxvj8tsc63l4x5stzdmrcfne6w68v3gpvs76s37er0xr58rpxdws5e094x278lpzuclf3katssqvysg4hj6vh6av92pdxy63v0p8ghfw2m5m8zgmjsr385emek0q6suyyu4999nu68ql6wqj8ldp044zdz26qklx3kxeegplljufn0328qka9rwk44063yth02az0s4kyqqnzx07459qjqxljvjs9qyunnkppplkpvdcmey4yjfm4zsen9094pqgng0xve3qaewk29zzcf998jjde2alp2vj033datjexdm2nfqujyqr042pqasrjvvf2rujr4kg4kek49ww0h2fxxzshj79yzusprfljvgaf2eplh5n6cm2zvapt2r65v9xx7xfhyvj359fc9j7xw5g59zm62zhnjg3gkaj5z7959ss5nzn2uv9hkjnzz8nmqtt9csz7dgucnwapgdsya7zks0lt4rz0ywrddvwwzr9l0k6rk6uck4ydza9qqjr3m7gnldzg2y28ys0awtde0z462w93gechrx8zp7fyedhlupe98hz7gn6nt9zyhhgkkeh4njytwa64vcgc7334nhwepwajtqgp7gwv9nz3dme6z44hjzw9c9dxakzp8fyjfatk5p9g2dd06gef546afsc2tw74qvc2h272xe6n4qqpkx2xz8qt9fdx4qwfljxah4q6yhukjzfz2fehxrnsd9m29yu0hrr6d7u6h4qnpx2hwdsgjpecemvjpej55ej20f80kg37x096n9t6setpw5v6p0unw6p4z757wjyx6f833y0hhwd4q970559pc0me3lnu86eqwgpw2se8qudpxwyu22ujylwmzwxjhxpca4nphegm5tpht0gnkpsl8p5667kxqfph8lu4z7ccjx4h9smk93p7hdn4cd6g4gvscpdw5e8tu2utlxcrhustdqp6e34st3yt2fumu8f374he8wpgqnpks3w32x6qmhf6rxrqp2nzkj2v7kqsy6m5wrcnen24k086wcun7q3pkjn54jqqfjvnh3m63tumk7zffsxznhj9jztckxesdpjx690qkp67d7rfyxapyqnq3f6x26edcpqsxptrnzn4r5rxqszhnq7lmyd4uac59acz5v7rty86czvxns6wcy2reurxduepdqmh4fxdu2msqas4pxcgj46tprm964p5d2ennatzucwpxgx2z066qsjdv4prpdktz86uf0h3xk7q7u8y799lsju30ucprzmeedgdq2jpvx6z6sfry4xugeuyk545w4lcdh9m0lffql0mhfundw6xxgm4kwj7wpyed0vuqadkqmxc2xulmfd60xcrh8ss489mygp6mqax6ydal3k222r556lfxgvcndmvskuej7wrqsyzkjl0yxd8avvdaqymfk5fctsqxn8lsyzqyl9h6wdyuhvl4nmmzx2t9n0txu90pvhwvjcjam920psu4qd9zxfxztx7nqq03ucpsxfc9acxzda9j8hq6mlg25s8v7h00zjmqgwflu03p56pukkf
    lastmodified: "2026-10-04T10:15:35Z"
    mac: ENC[AES256_GCM,data:4o4gHFzZKKJiLSRqcB+VqhCzRxC0Llqh+WFmr8slTfAPo4UViO5MLms3qvjAr+dRd0k396tP2CzIMucfZmg6O0tmVsKqySF9m9yLXC6jOA+I8RLM1U160NE5W9UjDD+RvpRPD2TRb3tRWD+ZX7+c2jzgX5KrLcUeXOwbXWx+OBc=,iv:Un1OhohDtyVSCeFeqcVutfeDaYH5m9NghWq2I5R2BUw=,tag:6VbXKkqBuHPE8vYR7sRkvQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
