- name: Playbooks | Fedora CoreOS bootc rebase
  ansible.builtin.import_playbook: fedora-coreos-bootc-rebase.yaml

- name: Playbooks | tailscale
  ansible.builtin.import_playbook: tailscale.yaml

- name: Playbooks | create user core
  ansible.builtin.import_playbook: user-core.yaml

- name: Playbooks | create user emergency
  ansible.builtin.import_playbook: user-emergency.yaml
  
- name: Playbooks | update ssh authorized keys
  ansible.builtin.import_playbook: update-ssh-authorized-keys.yaml
  
- name: Playbooks | enable linger
  ansible.builtin.import_playbook: enable-linger.yaml
  
- name: Playbooks | Sysctl
  ansible.builtin.import_playbook: sysctl.yaml
  
- name: Playbooks | mask-docker-service
  ansible.builtin.import_playbook: mask-docker-service.yaml

- name: Playbooks | fish shell
  ansible.builtin.import_playbook: fish.yaml

- name: Playbooks | scala-cli
  ansible.builtin.import_playbook: scala-cli.yaml

- name: Playbooks | ntfy-server-boot service and timer
  ansible.builtin.import_playbook: ntfy-server-boot.yaml

- name: Playbooks | update via dnf
  ansible.builtin.import_playbook: update-via-dnf.yaml

- name: Playbooks | packages
  ansible.builtin.import_playbook: packages.yaml

- name: Playbooks | common functions
  ansible.builtin.import_playbook: common-functions.yaml

- name: Playbooks | DNS
  ansible.builtin.import_playbook: dns.yaml

- name: Playbooks | path
  ansible.builtin.import_playbook: path.yaml

- name: Playbooks | Podman
  ansible.builtin.import_playbook: podman.yaml

- name: Playbooks | Incus
  ansible.builtin.import_playbook: incus-via-podman.yaml

- name: Playbooks | Syncthing
  ansible.builtin.import_playbook: syncthing.yaml

- name: Playbooks | Caddy
  ansible.builtin.import_playbook: caddy.yaml

- name: Playbooks | MariaDB
  ansible.builtin.import_playbook:

- name: Playbooks | PostgresDB
  ansible.builtin.import_playbook:

- name: Playbooks | CryptPad
  ansible.builtin.import_playbook:

- name: Playbooks | FileBrowser
  ansible.builtin.import_playbook:

- name: Playbooks | FileStash
  ansible.builtin.import_playbook:

- name: Playbooks | SftpGo
  ansible.builtin.import_playbook:

- name: Playbooks | Gemini CLI #TODO: convert to podman
  ansible.builtin.import_playbook: gemini-cli.yaml

- name: Playbooks | Let's Encrypt
  ansible.builtin.import_playbook:

- name: Playbooks | Cronicle #TODO: convert to podman
  ansible.builtin.import_playbook:

- name: Playbooks | ntfy
  ansible.builtin.import_playbook:
