- name: Enable login linger for a main user
  hosts: coreos:dnf:desktop
  gather_facts: false
  vars_files:
    - "../inventories/prod/host_vars/{{ inventory_hostname }}.yaml"
    - "../inventories/prod/secret_vars/{{ inventory_hostname }}.yaml"
    - "../inventories/prod/secret_vars/all.yaml"
  vars:
    main_user: core
  tasks:

    - name: Loginctl | enable-linger for '{{ main_user }}' user
      ansible.builtin.file:
        path: /var/lib/systemd/linger/{{ main_user }}
        state: touch
        owner: root
        group: root
        mode: '644'
      become: true
      register: linger_output
