- name: Fish functions
  hosts: coreos:dnf:desktop
  gather_facts: false
  vars_files:
    - "../inventories/prod/secret_vars/all.yaml"

  pre_tasks:
    - name: Fish | update local functions
      ansible.builtin.command:
        cmd: ./update-fish-functions.fish
        chdir: "{{ playbook_dir }}/.."
      delegate_to: localhost
      run_once: true
      changed_when: false

    - name: Gather per-host secret files
      ansible.builtin.include_vars:
        file: "{{ item }}"
      loop:
        - "../inventories/prod/secret_vars/{{ inventory_hostname }}/base.yaml"
      when: lookup('ansible.builtin.fileglob', item) | length > 0

  tasks:
    
    - name: Fish | rsync functions
      ansible.posix.synchronize:
        src: "../files/functions/"
        dest: "/home/{{ main_user }}/.config/fish/functions/"
        delete: yes
        checksum: yes
        times: no
        owner: no
        group: no
        perms: no
