- name: Install fnm CLI
  hosts: coreos:dnf:desktop
  gather_facts: true
  vars_files:
    - "../inventories/prod/host_vars/{{ inventory_hostname }}.yaml"
    - "../inventories/prod/secret_vars/{{ inventory_hostname }}.yaml"
    - "../inventories/prod/secret_vars/all.yaml"
  vars:
    main_user: core
  tasks:

    - name: Install fnm CLI | install 'fnm' and NodeJS
      ansible.builtin.shell: |
        set -euo pipefail
        IFS=$'\n\t'

        curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
        /home/{{ main_user }}/.local/share/fnm/fnm install 22
      args:
        executable: /usr/bin/bash
      when:
        - ansible_pkg_mgr in ['atomic_container', 'dnf', 'dnf5']
      register: node_install_output
      changed_when: "'warning: Version already installed at' not in node_install_output.stderr"
      
    - name: Install fnm CLI | setup fish shell
      ansible.builtin.template:
        src: ../files/fmn/fnm.fish
        dest: /home/{{ main_user }}/.config/fish/conf.d/fnm.fish
        owner: "{{ main_user }}"
        group: "{{ main_user }}"
        mode: '644'
      when:
        - ansible_pkg_mgr in ['atomic_container', 'dnf', 'dnf5']
    
    - name: Install fnm CLI | setup bash shell
      ansible.builtin.template:
        src: ../files/fnm/fnm.bashrc
        dest: /home/{{ main_user }}/.bashrc.d/fnm.bashrc
        owner: "{{ main_user }}"
        group: "{{ main_user }}"
        mode: '644'
      when:
        - ansible_pkg_mgr in ['atomic_container', 'dnf', 'dnf5']
