- name: Test
  hosts: all
  gather_facts: true
  vars_files:
    - "../inventories/prod/host_vars/{{ inventory_hostname }}.yaml"
    - "../inventories/prod/secret_vars/{{ inventory_hostname }}.yaml"
    - "../inventories/prod/secret_vars/all.yaml"
#  become: true
#  vars_prompt:
#    - name: dir
#      prompt: dir to eza
#      private: false
  tasks:

#    - name: Test | var in shell
#      ansible.builtin.shell: |
#        eza -ahl /home/core/{{ dir }}
#      register: test
#      changed_when: test.rc != 0

    - name: Test | become
      ansible.builtin.shell: |
        echo $(whoami)
      register: test

    - name: Debug
      ansible.builtin.debug:
        var: test

    - name: Test | become2
      become: true
      ansible.builtin.shell: |
        echo $(whoami)
      register: test

    - name: Debug
      ansible.builtin.debug:
        var: test
#
#    - name: Debug
#      ansible.builtin.debug:
#        var: test
#
#    - name: Display all Ansible facts
#      ansible.builtin.debug:
#        var: ansible_facts
#
#    - name: Display virtualization_tech_guest Ansible fact
#      ansible.builtin.debug:
#        var: ansible_facts['virtualization_tech_guest']
#
#    - name: "'docker.service' in ansible_facts.services"
#      ansible.builtin.debug:
#        var: ansible_facts.services['docker']
#    - name: Test | shell
#      ansible.builtin.shell: |
#        eza -ahl .
#      register: test
#      changed_when: test.rc != 0
#
#    - name: Debug
#      ansible.builtin.debug:
#        var: test
