- name: test-local
  hosts: all
  gather_facts: false
  tasks:

    - name: Copy the file to the target location
      ansible.builtin.copy:
        src: ../files/scala-test.scala
        dest: /tmp/scala-test.scala
        mode: '700'
      debugger: on_failed

#    - name: Test | eza
#      ansible.builtin.shell: |
#        eza -ahl /tmp
#      register: test
#
#    - name: Debug
#      ansible.builtin.debug:
#        var: test.stdout
#
#    - name: Test | printenv
#      ansible.builtin.shell: |
#        printenv
#      register: test
#      changed_when: test.rc != 0
#
#    - name: Debug
#      ansible.builtin.debug:
#        var: test.stdout

    - name: Execute the copied file
      ansible.builtin.shell: |
        /tmp/scala-test.scala kuba 38
      register: scala_test_output

    - name: Debug
      ansible.builtin.debug:
        var: scala_test_output.stdout
