- name: Update ssh authorized keys
  hosts: all
  gather_facts: false
  serial: 4
  vars_files:
    - "../vars/{{ inventory_hostname }}.yaml"
  vars:
    main_user: core
  tasks:

    - name: SSH | Create authorized_keys.d directory
      ansible.builtin.file:
        path: /home/{{ main_user }}/.ssh/authorized_keys.d
        state: directory
        mode: '700'
        owner: "{{ main_user }}"
        group: "{{ main_user }}"

    - name: SSH | Update authorized keys
      ansible.builtin.shell: |
        set -o pipefail
        set -e
        
        authorized_keys_dir=/home/{{ main_user }}/.ssh/authorized_keys.d
        authorized_keys_file=$authorized_keys_dir/ansible
        
        if [[ -f "$authorized_keys_file" ]]; then
          echo "$authorized_keys_file EXISTS"
        
          if cmp -s "$authorized_keys_file" <(curl -sSLf https://kuba86.com/ssh.txt); then
            echo "The files are identical."
          else
            echo "The files are different. Updating..."
            curl -sSLf https://kuba86.com/ssh.txt > "$authorized_keys_file"
          fi

        else
          echo "$authorized_keys_file DOES NOT EXISTS. Updating..."
          curl -sSLf https://kuba86.com/ssh.txt > "$authorized_keys_file"
          chmod 600 "$authorized_keys_file"
        fi
      register: ssh_update_output
      changed_when: "'Updating...' in ssh_update_output.stdout"
      become: true
      become_user: "{{ main_user }}"
