- name: Update all packages via dnf
  hosts: dnf
  gather_facts: true
  vars_files:
    - "../inventories/prod/host_vars/{{ inventory_hostname }}.yaml"
    - "../inventories/prod/secret_vars/{{ inventory_hostname }}.yaml"
    - "../inventories/prod/secret_vars/all.yaml"
  tasks:

    - name: Upgrade all packages
      become: true
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: true
      when:
        - ansible_pkg_mgr in ['dnf', 'dnf5']
