- name: Setup 'core' user
  hosts: all
  gather_facts: true
  serial: 4
  vars_files:
    - "../inventories/prod/secret_vars/{{ inventory_hostname }}.yaml"
  vars:
    core_user_pass_hash:
  tasks:

    - name: Add the user 'core'
      become: true
      ansible.builtin.user:
        name: core
        create_home: true
        # time mkpasswd --method=yescrypt --rounds 11 dummy_password
        password: "{{ core_user_pass_hash }}"
        state: present
        append: true
        groups:
          - wheel
