host_name: ENC[AES256_GCM,data:hXGhke0onXflq0DgCPQ=,iv:515hD0e563Tciy77R/TdTg9YquCJ1fVjLW7mubVJyXI=,tag:EgB/LqN5tCtKk7FNjdGuZg==,type:str]
main_user: ENC[AES256_GCM,data:U0yyjw==,iv:ecmcRYNTQ4hhJ2bgvIL1zy5qhHmwv09ok+JPklLo4cE=,tag:GxudhVz1/rDw/r6z+u6Upg==,type:str]
ansible_user: ENC[AES256_GCM,data:1GyXUA==,iv:oqC3ifg/gZ9dnpNzaeh4zDqLTamDgdKuZw48gbIoHic=,tag:QiqQjeWaG7lRHUOujbAzkQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:BWR+6MV85H4aOXo=,iv:qr7iMo5hQG1Jt1f4nCRpU6Sw/SZ563B5olnrPk+NFRU=,tag:wszgoaGDKUcJXd8iAIr+pQ==,type:str]
podman_userns: ENC[AES256_GCM,data:GzoEXXcSSwyYqbctoJE=,iv:GjuWGik7YEk0W9LAcvKrvjGTJis1Qr7g2PIoQFUblLk=,tag:zpMSrLYquxu44oeEDPcKMQ==,type:str]
DNS: ENC[AES256_GCM,data:NOHQGpucUGeoLnT9oOAV5JJP5gW2lf++jKgZbqzrtrNDqpoolpDMHSoI2JlVbJUgr2Pv0Mi1GcM4LXXhWCrGiebmqgFxyGC8wPqZTwJW8yKBlP64gYtrGIwn8hj/n+PPePsVZnXC6bezphcBG0r7n7nYDv5zfVwM1Ylnj10zLCSZTizvQyfJUJq7av/MjNNNwgWwLqZM5LoYb2C6rnS0xkTULtBReRO46tcO5F9T6EM61jcpmIDZR5W0+g==,iv:wLAM8awrv1nbwVuRDXJr/CUC0+E+wyYuP+qP5FZ1ZRw=,tag:+13ymXADPL8ZErNU10l6Yw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEU4Kzk3cGwy
            a2RrVVA0S0s3bitNUUlDU1Rrb0dNVHpHbTUvQ1N3NmZiV3VYaXBmeExnM3pzemxQ
            N08xRUN6Tk82T2tFbWk4eWpqVDd0dERvWW5tY0FwdWJoNU9KNjBNUnk5RmZyaFZ0
            UmZpZ09SL1Z1Rzh0WU9PNHpoaTBpeCtzWHcxR2hhWVlkNEhib1Uwc1FEL2phVk90
            bk9YVUFDOXNueitiZVJLL21JeEdCUklBTm0xb09zZ1NjU0Q4c1lCTVVMRDJXRlV0
            QkV3ckxXeVBIdHJPSmZvQmRhY2RsR0RJK3N6Rmh5U1A2b3FtVFlrYzNub2xPREY5
            S3BQZVJCSlpGNFFsQUt5TDF1cTRsZm9TYks5UVZJd1c2WGhJNzhQUnZCaHlmRms2
            cTRuSkRNSTNaTjlxQ2p6NC9LV0pzMWZvNUtZaWZ5WTZCbnI1UVZoRGJ2aS9kTFVD
            VThNbGlaL0Jhc21jZlVjUll1OGFqL1Q3SnhWTTNnNmw3dWRXbzlmVmFnOVVpQld4
            TDBrMU9SV00yakx5eitPNlJvRzM2djc3bkpCSkthQ1FZMUlUd1ZpdUhYVWdlYUM0
            Z0FYMXBPUVZWSzVia1ZHWk05bk4vc2doU2RSY2RZaHgzM1dHTXpDcnJlVmw5T0hT
            azN1RWVuN01JREVZbGR4TlJ6TDFHY3VTZnpYakU1RjIvNkFwTzdQQjRPUkZuck0y
            b2Foa016UFVuenl3WFJZVG8zc0g5QWg3TVJIN3BYYlZUS1R1d2UyZ21LeDN1bjRy
            MG5qc00wYnlzVVR5bkgzR09Sa0cvNkRjdjhESjFtTDJBZzZ4R01YeU1MNktMRHo3
            ZVM0MXpnSnpRRFU4aXFXZklaSjlIcjJ0cjZ2akV3bW5yUlhoU25GMmZqTjJxRFRi
            WHdpa1ErbVJQa1Y1V21yWUlYWWxOa0dWMmM2VzVaVWsxd1ZWUFlZMXVWZGtBOEhS
            WEw5K3dZMzg1UGVQZWJ1aGFEOE5TU2dKMjNDSGxvWUJySUtHbDJrODFObWphS09Z
            ZjUvTVFPL2FMbHd4WWR3VmtyZVVJWGZDMDNJRlEwUW9GWk41VkwxZ21JdUlDeFBJ
            cWt6a0hRM05ZNWVDeW8xbFI3R0h3YlQycW5zMEVEZEJtQWdwTWo0RDBIZ2ZlaWhz
            Wm1obTVaVEtxUGF5TnBoZWJWRWdmc25ZTnlTYWJLU2VSM3JqTVJkVURXRW9nSUZX
            UURDVmxMTWhaMmI3THh3Q0sxSU1JOWNkMUozckw4VDNGRXRqbzV3UENJeHJ1WGVZ
            UTJjUFhlbTAyNm94NkNhaTNNeFIySDlHTUN0TGw2SVl3TWhXMkFRYkRPTnpQQ2tC
            alJkYmlnK2NQcFVFVUhzeWt5MnJaR0IybjBjcDY2akhJUU9hQlovbjhpNGpaYUdy
            cnkzMFZBSGcxNzY2MW5pWlRFL0hWbFBET2R3WnJDRXB5QzcxaEdTalkxT1B4N0tD
            c0dyczJIbEJvblRQQ0l6dlhBSnBuWkNSYW9kbEpzSTRjbVZDbnZmL0ExWHQ3Vzh0
            NXdjODAxbVZONlU3bFFTTWw2ZkRYWjRYLzF0ZnhlTkhHNkFjQUptME5IT0VsRWdU
            TVAwclBuSUdmR0dzL3FlU2hIRytISkp6aFRETVc2cTdPMjhhS2EzOXBsTEtHNjIy
            OFp2bWFnUzFEeGxNNVAxMG1jK0FTRHlkTHFFdWRMRjJkKy90blFXMk9jajZYOUtJ
            T0FsQSsveHhZSG1GSitkVFVydTk4U29rTTFHZjRKelZCdE1DWmhLVmlDak9ITGZh
            Q0pidTRUd2tVeHhCL0JQdDVaclJ2enhrUWNHdHYrZXJva0FkdXYyS2JwbnBXVUNK
            N0FtdytuRmJZUGJkUFFKMVRQWjlDZHJJOTdsRTliS3hrZmpwRnZsY3RPaEJEWlZt
            VkVHd2ordFhkVDVKQWNvVjhUU1pvaEZjbnBjN25rV3pLeUdhM2NQTTgyeE1KZwpB
            SDhkTHBsMlErVnUrUVkvb3NtODhtMmV0a2hBcUtSaElEbVdsbkVzN2VJCi0tLSB3
            WldvSnpMTDc4SzBaSDFJVnc2MTRiQkRkcFJ0RWIvNm5BZzRRYkQyUzdZCmP0S8h6
            sx/+u0CZ5alB2Jpily/SJQTVlssGRO4ee8XrqqLS/79MGn+MxExuO8YP/kxuEiO6
            /xRG1VSckBmWh7U=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq18t5yaczngv0tw2809ycyhf2w2n4uj5yk9luyk4u3zfnnklylz2axxy4z3x9kzegtsc9s0xdlvaktsc0v5srrcmpev0yx6w2lwvgkyutnp7qfjadsps7g7uzzeak974465ej7dfk2pwfw7y98pljnlsh5puptqxm6zv2np92r92tz0f5mpz7hj604e2x8c0qu8vctgx8sexf2n2k502939fzzvzateztf3ykf58sxujzpkfqjq2eukdjgcrklr0t7n2vrvjzh6c5fqvn5fc4z8svcqm8m3yt8rqvhpf0zvy64wnvctq7urkff85ryd752s546pdk0390t6upnvhc80s5cvpf2je0ngyucxjffgucncwnsdrytgmmsrqwuzkkym27ygax356wzw0wmxvj8tsc63l4x5stzdmrcfne6w68v3gpvs76s37er0xr58rpxdws5e094x278lpzuclf3katssqvysg4hj6vh6av92pdxy63v0p8ghfw2m5m8zgmjsr385emek0q6suyyu4999nu68ql6wqj8ldp044zdz26qklx3kxeegplljufn0328qka9rwk44063yth02az0s4kyqqnzx07459qjqxljvjs9qyunnkppplkpvdcmey4yjfm4zsen9094pqgng0xve3qaewk29zzcf998jjde2alp2vj033datjexdm2nfqujyqr042pqasrjvvf2rujr4kg4kek49ww0h2fxxzshj79yzusprfljvgaf2eplh5n6cm2zvapt2r65v9xx7xfhyvj359fc9j7xw5g59zm62zhnjg3gkaj5z7959ss5nzn2uv9hkjnzz8nmqtt9csz7dgucnwapgdsya7zks0lt4rz0ywrddvwwzr9l0k6rk6uck4ydza9qqjr3m7gnldzg2y28ys0awtde0z462w93gechrx8zp7fyedhlupe98hz7gn6nt9zyhhgkkeh4njytwa64vcgc7334nhwepwajtqgp7gwv9nz3dme6z44hjzw9c9dxakzp8fyjfatk5p9g2dd06gef546afsc2tw74qvc2h272xe6n4qqpkx2xz8qt9fdx4qwfljxah4q6yhukjzfz2fehxrnsd9m29yu0hrr6d7u6h4qnpx2hwdsgjpecemvjpej55ej20f80kg37x096n9t6setpw5v6p0unw6p4z757wjyx6f833y0hhwd4q970559pc0me3lnu86eqwgpw2se8qudpxwyu22ujylwmzwxjhxpca4nphegm5tpht0gnkpsl8p5667kxqfph8lu4z7ccjx4h9smk93p7hdn4cd6g4gvscpdw5e8tu2utlxcrhustdqp6e34st3yt2fumu8f374he8wpgqnpks3w32x6qmhf6rxrqp2nzkj2v7kqsy6m5wrcnen24k086wcun7q3pkjn54jqqfjvnh3m63tumk7zffsxznhj9jztckxesdpjx690qkp67d7rfyxapyqnq3f6x26edcpqsxptrnzn4r5rxqszhnq7lmyd4uac59acz5v7rty86czvxns6wcy2reurxduepdqmh4fxdu2msqas4pxcgj46tprm964p5d2ennatzucwpxgx2z066qsjdv4prpdktz86uf0h3xk7q7u8y799lsju30ucprzmeedgdq2jpvx6z6sfry4xugeuyk545w4lcdh9m0lffql0mhfundw6xxgm4kwj7wpyed0vuqadkqmxc2xulmfd60xcrh8ss489mygp6mqax6ydal3k222r556lfxgvcndmvskuej7wrqsyzkjl0yxd8avvdaqymfk5fctsqxn8lsyzqyl9h6wdyuhvl4nmmzx2t9n0txu90pvhwvjcjam920psu4qd9zxfxztx7nqq03ucpsxfc9acxzda9j8hq6mlg25s8v7h00zjmqgwflu03p56pukkf
    lastmodified: "2026-10-04T10:15:35Z"
    mac: ENC[AES256_GCM,data:S7HNFGGZXPjPuxoGNgoy4LNi5vOAAJmfKIz/95fyXQS3LDT8yHaAVfBqlPP6YmRy4MpSFeHSQHoPLD64W01QG+qwumyz6hxucgROo/XdRu9kAcSH3NA4I6O1niF2WcY0xAjE19lhI7Nk3iM0XWz38wP3NiiWsk4G8jwQMsvjejQ=,iv:A0R32WOlhvbVIhDTkaG+zMnqTU05lxarPQodTAigKhg=,tag:ilFAQrnQKzRzWc8Yg3pwxA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
