host_name: ENC[AES256_GCM,data:uZ6qDpsc,iv:DWFyBWTbsnGpf4qiOC6zr8M+gIU5BlzkYPx6PQUw+mw=,tag:uTMjLfBt3a1jZwSw5pOZOA==,type:str]
main_user: ENC[AES256_GCM,data:N7Ee1Q==,iv:gCa0G4+7qSGjroW0ItOChFvZL9El4+hoirbfhKQsPK8=,tag:rSHNbr364XW3MbhUWpX62A==,type:str]
ansible_user: ENC[AES256_GCM,data:8xnz+w==,iv:l28GTrexRZQafnIDoGYJwdATsDu1BjuK3piT26zAQUc=,tag:2P8fAi8Z1mhQbRCLYblYpQ==,type:str]
podman_userns: ENC[AES256_GCM,data:MF8E4ST58brlaXflMCA=,iv:TqiLk9tm7xhtiDZhR/JZrA7T6NW2+NUr/Sz8JAwKRZk=,tag:mo1h2iQBy07/Jed0BIvwKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE9UbTdNWXpi
            ZWtqSkVUL1J0K3lEQ1Bvc3FMRVRaTXFUSE5EQkFDckozelFXeDFJYUlSYTlPajZr
            Y2dtT3p1VmJLSC9vejNOOEdTeStQbkxMeTBoNy80YTQ1bU94dEVnV1dNTTJxUW12
            eGNqNlJ1MEFWME1jZXU1MFRtOTZQZGFURy9IYTFhZ0VvbkU4bVJNNE1ZeDBzVjlt
            NlF0ZTVpajRDUEFnenVFU1JOUmJPeERKSzIwc1BFU1hqRUg2MzNMTjViYlRJZlhU
            VmlCRGFWMjc1WkphbmFPZzZ5czNEcXJ3WnlFeXlzOFNsT04rY1phNmx6QmswcnJi
            UjFaZnJPOGlQT2dhcXFZaWo0L0RsWlJVbldrOVJ0Y2VOcEVuaUh6SVZtaWxHWjZO
            ZU9XdzUyQzlEUm45ZlRrbHFpQTlUdFFZMmNSdzkrc0NzTjNaTGs4Q1BUVU9yN1Vr
            dTZzSXVmVjR1ME81elVMbm5ZUWNSRHYxQnFQcE00V1B4dzJHSmZ1dmZnb21HTjRo
            NTVENDVLWUVzeDhxdGdXdjBVWkkwTGRKSHdINEJyVytkME5tcE52bzlMc3RCOVVu
            dGFrdWM3MFJ2UXdOT1pVcEJTazlGdU1MMDFrcUFrUUxFTENiaWMreG1WTFFHTmVE
            LyttYklLVVFqZlFHZ0lkV2JHV1F5bjRPMkIyYzRwekgycnQwcDlFL1JHUGMzRk1C
            OEtQS3h6VWJJMjVDVzcycVZBNFJGU25QeHN4VUxDZnFZM3lDdm8yMEkzTGtScXdw
            M1E5bll3OW1jRHZ6VUhJTU0xWDJ4cUhGUTBPNkd6Y1ZmOFVhSmNMSDM3aUpMUDFl
            S3JySDlGcEcxdEVHV1BOVDdYMHBOSXFmZTJ5TjArM1YwOEpKOHlYRzVxcWRzaENl
            MWpWNm5OM045TE94R0Z3SnpibXZoUnhnWHgwU3RiSlBHc2YvVVg0OUh4SzE1K2Zu
            d2c2VEpVcTRUV0UrYlZ1L3FSUEN3UVRTM1NEZXFNRVVaVXljank5UzhNelhURlkr
            VU9vUWpNa1pJMENlVmlEU0FiTHpDYVJYN1l0cnozSy9NUGF2MVl2Sy9PME9xS1Z1
            RnZHNm9telhndEs2Mjdmb0lCYUJ6cFMvNEI4SFRWVGlaU1htTDkrcis4WDZkOWVU
            dzZ5c1dySXRwbzBvdkZuVTRjT0lkTUM2cGtUTHJlaUc1S2hZemt4Y1d5MW1LK3Nj
            RWYyTVB1WEdINGp1NXlmNzB4RnVkU211K2JKNE1zcG1QeTIvVVlUT2xQb1lTbU1k
            NGFHR0xjeXkxLzlRcGo1b25qSEtzTDlmTHlpSUVSakxuZjdGeVFZQXpGT0hvLzVX
            ZzZaVEVJWXJaK2JicENkbFovTXdnREhCT3NRUEwraytkZXI1RXNsM0hGQ0FoSjhE
            M3VGY0FsQlllaFF0Y2pjQStUWkhSWHVBRzhIN3R3ZWIxS3VUZ2xhOVl1RnZlcEZx
            azE5ekR2WS9keERZQjV0MXIzSllocEtvMnJGcllzSGJ6Y3dDbUFJM01SbHJ6cTVD
            ZnFTTXVsUE1iUWxlZUVLcE5JcnJwc1JqeVovY2diWnQrdENwMFRKMkw5VlJXd1kw
            WHV0V1ljRzl5VElVc3k1V0hpbHNqdSsxK1JpNkl6UTFQR29jbUYxTFErZzJGbFZP
            OU9oa1NITGE5bHVlazFBSmxFRkJmUjRTNGlReTFZaXRkaXAvMVRsRitQSnkvQlRE
            T2FKM0FNN2MrN3ZwaW9MRGkzMDFBOHFLTWRxenNHQmJBK2lYdzJCdFV0QzZZWnc1
            MWs2RytnVGZVZGhXNWNqbXJ0L1NLRmVDaFZaNHZ1UjAyb2hYMWdFSzZRZTZCblJu
            dnR5cFQ2MDc2YmZqeVhPSjZFTjB5eHhwTWpTVVlROHJ6Y1lsMjE0U1UxK0xtdW13
            QkJQeW52UDVEdkg5Q0MwUDZYYnAvWjZNN0cvanFWNk9rQ3FaK3RLWlEwQlBZUQpR
            U25rdlp6OVpoeTl2Z0ljRzRyTk4ramZmTTdHR1R5dEZ2bUF6U3FHTFIwCi0tLSAw
            UEFDZExBWGtsODd5MlVxN2g1Z28zZy85SjcvNTF3L1ZkYTlzRFU1TGZvCh0OlO5K
            5LHj+6EEh6Sr5CyPC+9ovuLRsfjYJfHQFRINpd1Anvv59qQIenC1PT0hNsubIAAb
            oJdxMjXkoRK3Wes=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq18t5yaczngv0tw2809ycyhf2w2n4uj5yk9luyk4u3zfnnklylz2axxy4z3x9kzegtsc9s0xdlvaktsc0v5srrcmpev0yx6w2lwvgkyutnp7qfjadsps7g7uzzeak974465ej7dfk2pwfw7y98pljnlsh5puptqxm6zv2np92r92tz0f5mpz7hj604e2x8c0qu8vctgx8sexf2n2k502939fzzvzateztf3ykf58sxujzpkfqjq2eukdjgcrklr0t7n2vrvjzh6c5fqvn5fc4z8svcqm8m3yt8rqvhpf0zvy64wnvctq7urkff85ryd752s546pdk0390t6upnvhc80s5cvpf2je0ngyucxjffgucncwnsdrytgmmsrqwuzkkym27ygax356wzw0wmxvj8tsc63l4x5stzdmrcfne6w68v3gpvs76s37er0xr58rpxdws5e094x278lpzuclf3katssqvysg4hj6vh6av92pdxy63v0p8ghfw2m5m8zgmjsr385emek0q6suyyu4999nu68ql6wqj8ldp044zdz26qklx3kxeegplljufn0328qka9rwk44063yth02az0s4kyqqnzx07459qjqxljvjs9qyunnkppplkpvdcmey4yjfm4zsen9094pqgng0xve3qaewk29zzcf998jjde2alp2vj033datjexdm2nfqujyqr042pqasrjvvf2rujr4kg4kek49ww0h2fxxzshj79yzusprfljvgaf2eplh5n6cm2zvapt2r65v9xx7xfhyvj359fc9j7xw5g59zm62zhnjg3gkaj5z7959ss5nzn2uv9hkjnzz8nmqtt9csz7dgucnwapgdsya7zks0lt4rz0ywrddvwwzr9l0k6rk6uck4ydza9qqjr3m7gnldzg2y28ys0awtde0z462w93gechrx8zp7fyedhlupe98hz7gn6nt9zyhhgkkeh4njytwa64vcgc7334nhwepwajtqgp7gwv9nz3dme6z44hjzw9c9dxakzp8fyjfatk5p9g2dd06gef546afsc2tw74qvc2h272xe6n4qqpkx2xz8qt9fdx4qwfljxah4q6yhukjzfz2fehxrnsd9m29yu0hrr6d7u6h4qnpx2hwdsgjpecemvjpej55ej20f80kg37x096n9t6setpw5v6p0unw6p4z757wjyx6f833y0hhwd4q970559pc0me3lnu86eqwgpw2se8qudpxwyu22ujylwmzwxjhxpca4nphegm5tpht0gnkpsl8p5667kxqfph8lu4z7ccjx4h9smk93p7hdn4cd6g4gvscpdw5e8tu2utlxcrhustdqp6e34st3yt2fumu8f374he8wpgqnpks3w32x6qmhf6rxrqp2nzkj2v7kqsy6m5wrcnen24k086wcun7q3pkjn54jqqfjvnh3m63tumk7zffsxznhj9jztckxesdpjx690qkp67d7rfyxapyqnq3f6x26edcpqsxptrnzn4r5rxqszhnq7lmyd4uac59acz5v7rty86czvxns6wcy2reurxduepdqmh4fxdu2msqas4pxcgj46tprm964p5d2ennatzucwpxgx2z066qsjdv4prpdktz86uf0h3xk7q7u8y799lsju30ucprzmeedgdq2jpvx6z6sfry4xugeuyk545w4lcdh9m0lffql0mhfundw6xxgm4kwj7wpyed0vuqadkqmxc2xulmfd60xcrh8ss489mygp6mqax6ydal3k222r556lfxgvcndmvskuej7wrqsyzkjl0yxd8avvdaqymfk5fctsqxn8lsyzqyl9h6wdyuhvl4nmmzx2t9n0txu90pvhwvjcjam920psu4qd9zxfxztx7nqq03ucpsxfc9acxzda9j8hq6mlg25s8v7h00zjmqgwflu03p56pukkf
    lastmodified: "2026-10-04T10:15:34Z"
    mac: ENC[AES256_GCM,data:94ZxfJH9VNi/O3kPPQoSIMjZGCWlApdc+Ke/1XnxdbDfdRK+8IigeiRtC9jiYuFU11K/doj8GlY7GvHEQ56usI8waXVWMFn+Ys51oUfxQtSHV5BVujt9tiMIEAvECt1L9O76HsYq30f79InaBXowDLIqCF/hK6qW13BO8emdcrM=,iv:KPmSixYdGR6vre6w4zGNMyMVlTckppi5waJVtYmoK1c=,tag:idsIQu0vBu5YAB2xgIqMEg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
